CREATE TABLE IF NOT EXISTS schools (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS careers (
    id BIGSERIAL PRIMARY KEY,
    code VARCHAR(30) NOT NULL UNIQUE,
    name VARCHAR(180) NOT NULL,
    school_id BIGINT NOT NULL REFERENCES schools(id),
    duration_terms SMALLINT NOT NULL CHECK (duration_terms > 0),
    modality VARCHAR(20) NOT NULL CHECK (modality IN ('ON_CAMPUS', 'ONLINE', 'HYBRID')),
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'INACTIVE')),
    image_url VARCHAR(500)
);

CREATE INDEX IF NOT EXISTS idx_careers_school_id ON careers(school_id);
CREATE INDEX IF NOT EXISTS idx_careers_name_lower ON careers(LOWER(name));

CREATE TABLE IF NOT EXISTS pensum (
    id BIGSERIAL PRIMARY KEY,
    career_id BIGINT NOT NULL REFERENCES careers(id),
    term_number SMALLINT NOT NULL CHECK (term_number > 0),
    subject_name VARCHAR(200) NOT NULL,
    credits SMALLINT NOT NULL CHECK (credits BETWEEN 1 AND 5),
    UNIQUE (career_id, term_number, subject_name)
);

CREATE INDEX IF NOT EXISTS idx_pensum_career_id ON pensum(career_id);

-- Migra bases creadas con el nombre anterior sin fallar en instalaciones nuevas.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'careers' AND column_name = 'duration_semesters'
    ) AND NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'careers' AND column_name = 'duration_terms'
    ) THEN
        ALTER TABLE careers RENAME COLUMN duration_semesters TO duration_terms;
    END IF;
END $$;

INSERT INTO schools (name)
VALUES
    ('Escuela de Administración'),
    ('Escuela de Artes y Comunicación'),
    ('Escuela de Ciencias Sociales'),
    ('Escuela de Contabilidad y Finanzas'),
    ('Escuela de Derecho'),
    ('Escuela de Español'),
    ('Escuela de Idiomas'),
    ('Escuela de Informática'),
    ('Escuela de Ingenierías'),
    ('Escuela de Matemáticas'),
    ('Escuela de Mercadeo y Negocios Internacionales'),
    ('Escuela de Turismo')
ON CONFLICT (name) DO NOTHING;

INSERT INTO careers (code, name, school_id, duration_terms, modality, status)
SELECT
    program.code,
    program.name,
    school.id,
    program.duration_terms,
    program.modality,
    program.status
FROM (VALUES
    ('LMF', 'Licenciatura en Educación Secundaria: Matemática y Física', 'Escuela de Idiomas', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('ISC', 'Ingeniería de Sistemas de Computación', 'Escuela de Informática', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('ISO', 'Ingeniería de Software', 'Escuela de Informática', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('INE', 'Ingeniería Eléctrica', 'Escuela de Ingenierías', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('IEL', 'Ingeniería Electrónica', 'Escuela de Ingenierías', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('IND', 'Ingeniería Industrial', 'Escuela de Ingenierías', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('ADM', 'Licenciatura en Administración de Empresas', 'Escuela de Administración', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('ATH', 'Licenciatura en Administración Turística y Hotelera', 'Escuela de Turismo', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('CIN', 'Licenciatura en Cinematografía', 'Escuela de Artes y Comunicación', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('CDG', 'Licenciatura en Comunicación Digital', 'Escuela de Artes y Comunicación', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('CPM', 'Licenciatura en Comunicación y Periodismo Multiplataforma', 'Escuela de Artes y Comunicación', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('CON', 'Licenciatura en Contabilidad', 'Escuela de Contabilidad y Finanzas', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('DER', 'Licenciatura en Derecho', 'Escuela de Derecho', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('DIN', 'Licenciatura en Diseño de Interiores', 'Escuela de Artes y Comunicación', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('DIG', 'Licenciatura en Diseño Gráfico', 'Escuela de Artes y Comunicación', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('ECO', 'Licenciatura en Economía y Ciencia de Datos', 'Escuela de Contabilidad y Finanzas', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('LEA', 'Licenciatura en Educación Artística', 'Escuela de Artes y Comunicación', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('LEF', 'Licenciatura en Educación, mención Lenguas Extranjeras: Francés', 'Escuela de Idiomas', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('LEI', 'Licenciatura en Educación, mención Lenguas Extranjeras: Inglés', 'Escuela de Idiomas', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('EST', 'Licenciatura en Estadística', 'Escuela de Matemáticas', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('FIN', 'Licenciatura en Finanzas', 'Escuela de Contabilidad y Finanzas', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('GAS', 'Licenciatura en Gastronomía y Arte Culinario', 'Escuela de Turismo', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('GOL', 'Licenciatura en Gestión de Operaciones y Logística', 'Escuela de Administración', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('LEL', 'Licenciatura en Lengua Española y Literatura Orientada a la Educación Secundaria', 'Escuela de Español', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('LME', 'Licenciatura en Matemática Orientada a la Educación Secundaria', 'Escuela de Matemáticas', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('MER', 'Licenciatura en Mercadotecnia', 'Escuela de Mercadeo y Negocios Internacionales', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('NIN', 'Licenciatura en Negocios Internacionales', 'Escuela de Mercadeo y Negocios Internacionales', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('PSO', 'Licenciatura en Psicología Organizacional', 'Escuela de Ciencias Sociales', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('PUB', 'Licenciatura en Publicidad', 'Escuela de Artes y Comunicación', 12, 'ON_CAMPUS', 'ACTIVE'),
    ('TS-ADS', 'Técnico Superior Analista Desarrollador de Software', 'Escuela de Informática', 6, 'ON_CAMPUS', 'ACTIVE'),
    ('TS-EM', 'Técnico Superior Ejecutivo de Marketing', 'Escuela de Mercadeo y Negocios Internacionales', 6, 'ON_CAMPUS', 'ACTIVE'),
    ('TS-APA', 'Técnico Superior en Animación y Postproducción Audiovisual', 'Escuela de Artes y Comunicación', 6, 'ON_CAMPUS', 'ACTIVE'),
    ('TS-CE', 'Técnico Superior en Contabilidad Empresarial', 'Escuela de Contabilidad y Finanzas', 6, 'ON_CAMPUS', 'ACTIVE'),
    ('TS-CRI', 'Técnico Superior en Criminalística', 'Escuela de Derecho', 6, 'ON_CAMPUS', 'ACTIVE'),
    ('TS-DAD', 'Técnico Superior en Dibujo Arquitectónico Digital', 'Escuela de Artes y Comunicación', 6, 'ON_CAMPUS', 'ACTIVE'),
    ('TS-DPE', 'Técnico Superior en Diseño y Producción Editorial', 'Escuela de Artes y Comunicación', 6, 'ON_CAMPUS', 'ACTIVE'),
    ('TS-ECI', 'Técnico Superior Ejecutivo en Comercio Internacional', 'Escuela de Administración', 6, 'ON_CAMPUS', 'ACTIVE'),
    ('TS-FIN', 'Técnico Superior en Finanzas', 'Escuela de Contabilidad y Finanzas', 6, 'ON_CAMPUS', 'ACTIVE'),
    ('TS-GE', 'Técnico Superior en Gestión de Eventos', 'Escuela de Artes y Comunicación', 6, 'ON_CAMPUS', 'ACTIVE'),
    ('TS-GSA', 'Técnico Superior en Gestión de Servicios de Alimentos y Bebidas', 'Escuela de Turismo', 6, 'ON_CAMPUS', 'ACTIVE'),
    ('TS-GL', 'Técnico Superior en Gestión Legal', 'Escuela de Derecho', 6, 'ON_CAMPUS', 'ACTIVE'),
    ('TS-L360', 'Técnico Superior en Logística 360 y Gestión de Materiales', 'Escuela de Administración', 6, 'ON_CAMPUS', 'ACTIVE'),
    ('TS-TH', 'Técnico Superior Turístico y Hotelero', 'Escuela de Turismo', 6, 'ON_CAMPUS', 'ACTIVE')
) AS program(code, name, school_name, duration_terms, modality, status)
INNER JOIN schools AS school ON school.name = program.school_name
ON CONFLICT (code) DO UPDATE SET
    name = EXCLUDED.name,
    school_id = EXCLUDED.school_id,
    duration_terms = EXCLUDED.duration_terms,
    modality = EXCLUDED.modality,
    status = EXCLUDED.status;

-- ============================================================
-- DATOS DEL PENSUM (generados automaticamente)
-- ============================================================
INSERT INTO pensum (career_id, term_number, subject_name, credits)
SELECT c.id, data.term, data.subject, data.credits
FROM (VALUES
    ('TS-L360', 1, 'Liderazgo', 2),
    ('TS-L360', 1, 'Ingles I', 3),
    ('TS-L360', 1, 'Espanol I', 3),
    ('TS-L360', 1, 'Gestion de Riesgos', 3),
    ('TS-L360', 2, 'Espanol II', 3),
    ('TS-L360', 2, 'Comercio Electronico', 3),
    ('TS-L360', 2, 'Historia Dominicana', 3),
    ('TS-L360', 2, 'Metodologia de la Investigacion', 3),
    ('TS-L360', 3, 'Contabilidad II', 4),
    ('TS-L360', 3, 'Comercio Internacional', 4),
    ('TS-L360', 3, 'Mercadotecnia II', 4),
    ('TS-L360', 3, 'Seminario de Grado', 4),
    ('TS-L360', 4, 'Redaccion Academica', 3),
    ('TS-L360', 4, 'Responsabilidad Social Empresarial', 2),
    ('TS-L360', 4, 'Finanzas Corporativas', 4),
    ('TS-L360', 4, 'Etica Profesional', 2),
    ('TS-L360', 5, 'Matematica Basica', 4),
    ('TS-L360', 5, 'Toma de Decisiones Gerenciales', 4),
    ('TS-L360', 5, 'Ingles II', 3),
    ('TS-L360', 5, 'Filosofia', 3),
    ('TS-L360', 6, 'Cadena de Suministro', 4),
    ('TS-L360', 6, 'Medio Ambiente y Sociedad', 2),
    ('TS-L360', 6, 'Administracion Publica', 3),
    ('TS-L360', 6, 'Derecho Empresarial', 3),
    ('TS-L360', 7, 'Emprendimiento', 3),
    ('TS-L360', 7, 'Ingles III', 3),
    ('TS-L360', 7, 'Estadistica General', 4),
    ('TS-L360', 7, 'Gestion del Cambio', 3),
    ('TS-L360', 8, 'Tecnologia de la Informacion', 3),
    ('TS-L360', 8, 'Auditoria Administrativa', 3),
    ('TS-L360', 8, 'Gestion de Operaciones', 4),
    ('TS-L360', 8, 'Negociacion y Resolucion de Conflictos', 3),
    ('TS-L360', 9, 'Administracion de Empresas', 4),
    ('TS-L360', 9, 'Innovacion Empresarial', 3),
    ('TS-L360', 9, 'Presupuesto Empresarial', 3),
    ('TS-L360', 9, 'Comportamiento Organizacional', 3),
    ('TS-L360', 10, 'Economia Empresarial', 4),
    ('TS-L360', 10, 'Planificacion Estrategica', 4),
    ('TS-L360', 10, 'Contabilidad I', 4),
    ('TS-L360', 10, 'Gestion de la Calidad', 3),
    ('TS-L360', 11, 'Mercadotecnia I', 4),
    ('TS-L360', 11, 'Gestion del Talento Humano', 4),
    ('TS-ECI', 1, 'Espanol I', 3),
    ('TS-ECI', 1, 'Metodologia de la Investigacion', 3),
    ('TS-ECI', 1, 'Gestion del Talento Humano', 4),
    ('TS-ECI', 1, 'Emprendimiento', 3),
    ('TS-ECI', 2, 'Gestion del Cambio', 3),
    ('TS-ECI', 2, 'Medio Ambiente y Sociedad', 2),
    ('TS-ECI', 2, 'Tecnologia de la Informacion', 3),
    ('TS-ECI', 2, 'Matematica Basica', 4),
    ('TS-ECI', 3, 'Espanol II', 3),
    ('TS-ECI', 3, 'Filosofia', 3),
    ('TS-ECI', 3, 'Economia Empresarial', 4),
    ('TS-ECI', 3, 'Gestion de la Calidad', 3),
    ('TS-ECI', 4, 'Innovacion Empresarial', 3),
    ('TS-ECI', 4, 'Ingles III', 3),
    ('TS-ECI', 4, 'Auditoria Administrativa', 3),
    ('TS-ECI', 4, 'Etica Profesional', 2),
    ('TS-ECI', 5, 'Presupuesto Empresarial', 3),
    ('TS-ECI', 5, 'Comercio Internacional', 4),
    ('TS-ECI', 5, 'Comportamiento Organizacional', 3),
    ('TS-ECI', 5, 'Planificacion Estrategica', 4),
    ('TS-ECI', 6, 'Ingles II', 3),
    ('TS-ECI', 6, 'Negociacion y Resolucion de Conflictos', 3),
    ('TS-ECI', 6, 'Toma de Decisiones Gerenciales', 4),
    ('TS-ECI', 6, 'Contabilidad II', 4),
    ('TS-ECI', 7, 'Estadistica General', 4),
    ('TS-ECI', 7, 'Derecho Empresarial', 3),
    ('TS-ECI', 7, 'Administracion Publica', 3),
    ('TS-ECI', 7, 'Redaccion Academica', 3),
    ('TS-ECI', 8, 'Liderazgo', 2),
    ('TS-ECI', 8, 'Ingles I', 3),
    ('TS-ECI', 8, 'Historia Dominicana', 3),
    ('TS-ECI', 8, 'Seminario de Grado', 4),
    ('TS-ECI', 9, 'Cadena de Suministro', 4),
    ('TS-ECI', 9, 'Gestion de Operaciones', 4),
    ('TS-ECI', 9, 'Contabilidad I', 4),
    ('TS-ECI', 9, 'Administracion de Empresas', 4),
    ('TS-ECI', 10, 'Responsabilidad Social Empresarial', 2),
    ('TS-ECI', 10, 'Mercadotecnia I', 4),
    ('TS-ECI', 10, 'Gestion de Riesgos', 3),
    ('TS-ECI', 10, 'Mercadotecnia II', 4),
    ('TS-ECI', 11, 'Finanzas Corporativas', 4),
    ('TS-ECI', 11, 'Comercio Electronico', 3),
    ('GOL', 1, 'Tecnologia de la Informacion', 3),
    ('GOL', 1, 'Mercadotecnia II', 4),
    ('GOL', 1, 'Espanol II', 3),
    ('GOL', 1, 'Estadistica General', 4),
    ('GOL', 2, 'Ingles I', 3),
    ('GOL', 2, 'Administracion de Empresas', 4),
    ('GOL', 2, 'Toma de Decisiones Gerenciales', 4),
    ('GOL', 2, 'Gestion del Cambio', 3),
    ('GOL', 3, 'Ingles II', 3),
    ('GOL', 3, 'Administracion Publica', 3),
    ('GOL', 3, 'Redaccion Academica', 3),
    ('GOL', 3, 'Filosofia', 3),
    ('GOL', 4, 'Medio Ambiente y Sociedad', 2),
    ('GOL', 4, 'Historia Dominicana', 3),
    ('GOL', 4, 'Planificacion Estrategica', 4),
    ('GOL', 4, 'Espanol I', 3),
    ('GOL', 5, 'Emprendimiento', 3),
    ('GOL', 5, 'Matematica Basica', 4),
    ('GOL', 5, 'Metodologia de la Investigacion', 3),
    ('GOL', 5, 'Auditoria Administrativa', 3),
    ('GOL', 6, 'Contabilidad I', 4),
    ('GOL', 6, 'Comercio Internacional', 4),
    ('GOL', 6, 'Etica Profesional', 2),
    ('GOL', 6, 'Liderazgo', 2),
    ('GOL', 7, 'Gestion de la Calidad', 3),
    ('GOL', 7, 'Ingles III', 3),
    ('GOL', 7, 'Finanzas Corporativas', 4),
    ('GOL', 7, 'Contabilidad II', 4),
    ('GOL', 8, 'Negociacion y Resolucion de Conflictos', 3),
    ('GOL', 8, 'Gestion del Talento Humano', 4),
    ('GOL', 8, 'Comercio Electronico', 3),
    ('GOL', 8, 'Mercadotecnia I', 4),
    ('GOL', 9, 'Seminario de Grado', 4),
    ('GOL', 9, 'Derecho Empresarial', 3),
    ('GOL', 9, 'Cadena de Suministro', 4),
    ('GOL', 9, 'Gestion de Riesgos', 3),
    ('GOL', 10, 'Economia Empresarial', 4),
    ('GOL', 10, 'Responsabilidad Social Empresarial', 2),
    ('GOL', 10, 'Innovacion Empresarial', 3),
    ('GOL', 10, 'Gestion de Operaciones', 4),
    ('GOL', 11, 'Presupuesto Empresarial', 3),
    ('GOL', 11, 'Comportamiento Organizacional', 3),
    ('ADM', 1, 'Filosofia', 3),
    ('ADM', 1, 'Emprendimiento', 3),
    ('ADM', 1, 'Derecho Empresarial', 3),
    ('ADM', 1, 'Espanol II', 3),
    ('ADM', 2, 'Economia Empresarial', 4),
    ('ADM', 2, 'Gestion de Operaciones', 4),
    ('ADM', 2, 'Responsabilidad Social Empresarial', 2),
    ('ADM', 2, 'Espanol I', 3),
    ('ADM', 3, 'Cadena de Suministro', 4),
    ('ADM', 3, 'Contabilidad II', 4),
    ('ADM', 3, 'Comercio Electronico', 3),
    ('ADM', 3, 'Gestion de la Calidad', 3),
    ('ADM', 4, 'Redaccion Academica', 3),
    ('ADM', 4, 'Comportamiento Organizacional', 3),
    ('ADM', 4, 'Seminario de Grado', 4),
    ('ADM', 4, 'Matematica Basica', 4),
    ('ADM', 5, 'Etica Profesional', 2),
    ('ADM', 5, 'Negociacion y Resolucion de Conflictos', 3),
    ('ADM', 5, 'Gestion del Cambio', 3),
    ('ADM', 5, 'Administracion Publica', 3),
    ('ADM', 6, 'Gestion del Talento Humano', 4),
    ('ADM', 6, 'Contabilidad I', 4),
    ('ADM', 6, 'Presupuesto Empresarial', 3),
    ('ADM', 6, 'Gestion de Riesgos', 3),
    ('ADM', 7, 'Ingles III', 3),
    ('ADM', 7, 'Liderazgo', 2),
    ('ADM', 7, 'Administracion de Empresas', 4),
    ('ADM', 7, 'Comercio Internacional', 4),
    ('ADM', 8, 'Mercadotecnia I', 4),
    ('ADM', 8, 'Mercadotecnia II', 4),
    ('ADM', 8, 'Ingles I', 3),
    ('ADM', 8, 'Innovacion Empresarial', 3),
    ('ADM', 9, 'Ingles II', 3),
    ('ADM', 9, 'Estadistica General', 4),
    ('ADM', 9, 'Metodologia de la Investigacion', 3),
    ('ADM', 9, 'Medio Ambiente y Sociedad', 2),
    ('ADM', 10, 'Historia Dominicana', 3),
    ('ADM', 10, 'Planificacion Estrategica', 4),
    ('ADM', 10, 'Tecnologia de la Informacion', 3),
    ('ADM', 10, 'Toma de Decisiones Gerenciales', 4),
    ('ADM', 11, 'Auditoria Administrativa', 3),
    ('ADM', 11, 'Finanzas Corporativas', 4),
    ('TS-GE', 1, 'Etica Profesional', 2),
    ('TS-GE', 1, 'Espanol II', 3),
    ('TS-GE', 1, 'Ingles II', 3),
    ('TS-GE', 1, 'Patrimonio Cultural', 3),
    ('TS-GE', 2, 'Emprendimiento', 3),
    ('TS-GE', 2, 'Matematica Basica', 4),
    ('TS-GE', 2, 'Enologia y Maridaje', 3),
    ('TS-GE', 2, 'Medio Ambiente y Sociedad', 2),
    ('TS-GE', 3, 'Tecnologia Aplicada al Turismo', 3),
    ('TS-GE', 3, 'Turismo Sostenible', 3),
    ('TS-GE', 3, 'Cruceros y Viajes', 3),
    ('TS-GE', 3, 'Espanol I', 3),
    ('TS-GE', 4, 'Ecoturismo', 3),
    ('TS-GE', 4, 'Estadistica General', 4),
    ('TS-GE', 4, 'Tecnologia de la Informacion', 3),
    ('TS-GE', 4, 'Administracion Hotelera', 4),
    ('TS-GE', 5, 'Historia Dominicana', 3),
    ('TS-GE', 5, 'Liderazgo', 2),
    ('TS-GE', 5, 'Operacion de Aerolineas', 3),
    ('TS-GE', 5, 'Negocios Turisticos', 3),
    ('TS-GE', 6, 'Metodologia de la Investigacion', 3),
    ('TS-GE', 6, 'Filosofia', 3),
    ('TS-GE', 6, 'Redaccion Academica', 3),
    ('TS-GE', 6, 'Mercadeo Turistico', 4),
    ('TS-GE', 7, 'Ingles III', 3),
    ('TS-GE', 7, 'Legislacion Turistica', 3),
    ('TS-GE', 7, 'Gestion de Eventos', 4),
    ('TS-GE', 7, 'Idiomas para Turismo', 3),
    ('TS-GE', 8, 'Ingles I', 3),
    ('TS-GE', 8, 'Introduccion al Turismo', 4),
    ('TS-GE', 8, 'Cocina Dominicana', 4),
    ('TS-GE', 8, 'Contabilidad Hotelera', 3),
    ('TS-GE', 9, 'Planificacion Turistica', 4),
    ('TS-GE', 9, 'Gastronomia Internacional', 4),
    ('TS-GE', 9, 'Gestion de Destinos', 4),
    ('TS-GE', 9, 'Geografia Turistica Dominicana', 4),
    ('TS-GE', 10, 'Protocolo y Etiqueta', 2),
    ('TS-GE', 10, 'Gestion de Alimentos y Bebidas', 4),
    ('TS-GE', 10, 'Turismo de Aventura', 3),
    ('TS-GE', 10, 'Calidad en el Servicio', 3),
    ('TS-GE', 11, 'Animacion Turistica', 3),
    ('TS-GE', 11, 'Reposteria y Panaderia', 4),
    ('TS-DPE', 1, 'Semiotica', 3),
    ('TS-DPE', 1, 'Portafolio Profesional', 4),
    ('TS-DPE', 1, 'Ingles I', 3),
    ('TS-DPE', 1, 'Emprendimiento', 3),
    ('TS-DPE', 2, 'Diseno Grafico I', 4),
    ('TS-DPE', 2, 'Etica Profesional', 2),
    ('TS-DPE', 2, 'Metodologia de la Investigacion', 3),
    ('TS-DPE', 2, 'Tecnologia de la Informacion', 3),
    ('TS-DPE', 3, 'Dibujo Artistico', 4),
    ('TS-DPE', 3, 'Espanol I', 3),
    ('TS-DPE', 3, 'Creatividad e Innovacion', 3),
    ('TS-DPE', 3, 'Manejo de Redes Sociales', 3),
    ('TS-DPE', 4, 'Estadistica General', 4),
    ('TS-DPE', 4, 'Ingles II', 3),
    ('TS-DPE', 4, 'Fotografia II', 4),
    ('TS-DPE', 4, 'Edicion de Video', 4),
    ('TS-DPE', 5, 'Medio Ambiente y Sociedad', 2),
    ('TS-DPE', 5, 'Matematica Basica', 4),
    ('TS-DPE', 5, 'Redaccion Periodistica', 4),
    ('TS-DPE', 5, 'Comunicacion Digital', 4),
    ('TS-DPE', 6, 'Redaccion Academica', 3),
    ('TS-DPE', 6, 'Ingles III', 3),
    ('TS-DPE', 6, 'Historia Dominicana', 3),
    ('TS-DPE', 6, 'Espanol II', 3),
    ('TS-DPE', 7, 'Marketing Digital', 3),
    ('TS-DPE', 7, 'Liderazgo', 2),
    ('TS-DPE', 7, 'Sonido y Mezcla', 3),
    ('TS-DPE', 7, 'Ilustracion Digital', 4),
    ('TS-DPE', 8, 'Estrategia de Contenidos', 3),
    ('TS-DPE', 8, 'Diseno Grafico II', 4),
    ('TS-DPE', 8, 'Filosofia', 3),
    ('TS-DPE', 8, 'Publicidad II', 4),
    ('TS-DPE', 9, 'Fotografia I', 4),
    ('TS-DPE', 9, 'Publicidad I', 4),
    ('TS-DPE', 9, 'Produccion Audiovisual', 4),
    ('TS-DPE', 9, 'Animacion 2D', 4),
    ('TS-DPE', 10, 'Produccion de Eventos', 3),
    ('TS-DPE', 10, 'Teoria del Color', 3),
    ('TS-DPE', 10, 'Tipografia', 3),
    ('TS-DPE', 10, 'Animacion 3D', 4),
    ('TS-DPE', 11, 'Historia del Arte', 3),
    ('TS-DPE', 11, 'Branding', 3),
    ('TS-DPE', 11, 'Direccion de Arte', 4),
    ('TS-DPE', 11, 'Guionismo', 3),
    ('TS-DPE', 12, 'Diseno Editorial', 4),
    ('TS-DAD', 1, 'Tipografia', 3),
    ('TS-DAD', 1, 'Ilustracion Digital', 4),
    ('TS-DAD', 1, 'Liderazgo', 2),
    ('TS-DAD', 1, 'Etica Profesional', 2),
    ('TS-DAD', 2, 'Matematica Basica', 4),
    ('TS-DAD', 2, 'Espanol I', 3),
    ('TS-DAD', 2, 'Sonido y Mezcla', 3),
    ('TS-DAD', 2, 'Filosofia', 3),
    ('TS-DAD', 3, 'Historia del Arte', 3),
    ('TS-DAD', 3, 'Medio Ambiente y Sociedad', 2),
    ('TS-DAD', 3, 'Estadistica General', 4),
    ('TS-DAD', 3, 'Publicidad I', 4),
    ('TS-DAD', 4, 'Metodologia de la Investigacion', 3),
    ('TS-DAD', 4, 'Dibujo Artistico', 4),
    ('TS-DAD', 4, 'Edicion de Video', 4),
    ('TS-DAD', 4, 'Branding', 3),
    ('TS-DAD', 5, 'Animacion 3D', 4),
    ('TS-DAD', 5, 'Redaccion Academica', 3),
    ('TS-DAD', 5, 'Tecnologia de la Informacion', 3),
    ('TS-DAD', 5, 'Comunicacion Digital', 4),
    ('TS-DAD', 6, 'Ingles I', 3),
    ('TS-DAD', 6, 'Ingles II', 3),
    ('TS-DAD', 6, 'Manejo de Redes Sociales', 3),
    ('TS-DAD', 6, 'Publicidad II', 4),
    ('TS-DAD', 7, 'Espanol II', 3),
    ('TS-DAD', 7, 'Fotografia II', 4),
    ('TS-DAD', 7, 'Creatividad e Innovacion', 3),
    ('TS-DAD', 7, 'Emprendimiento', 3),
    ('TS-DAD', 8, 'Historia Dominicana', 3),
    ('TS-DAD', 8, 'Fotografia I', 4),
    ('TS-DAD', 8, 'Ingles III', 3),
    ('TS-DAD', 8, 'Produccion Audiovisual', 4),
    ('TS-DAD', 9, 'Diseno Editorial', 4),
    ('TS-DAD', 9, 'Redaccion Periodistica', 4),
    ('TS-DAD', 9, 'Teoria del Color', 3),
    ('TS-DAD', 9, 'Guionismo', 3),
    ('TS-DAD', 10, 'Estrategia de Contenidos', 3),
    ('TS-DAD', 10, 'Direccion de Arte', 4),
    ('TS-DAD', 10, 'Semiotica', 3),
    ('TS-DAD', 10, 'Animacion 2D', 4),
    ('TS-DAD', 11, 'Produccion de Eventos', 3),
    ('TS-DAD', 11, 'Portafolio Profesional', 4),
    ('TS-DAD', 11, 'Diseno Grafico I', 4),
    ('TS-DAD', 11, 'Marketing Digital', 3),
    ('TS-DAD', 12, 'Diseno Grafico II', 4),
    ('TS-APA', 1, 'Tecnologia de la Informacion', 3),
    ('TS-APA', 1, 'Derecho Empresarial', 3),
    ('TS-APA', 1, 'Medio Ambiente y Sociedad', 2),
    ('TS-APA', 1, 'Ingles I', 3),
    ('TS-APA', 2, 'Ingles III', 3),
    ('TS-APA', 2, 'Administracion de Empresas', 4),
    ('TS-APA', 2, 'Matematica Basica', 4),
    ('TS-APA', 2, 'Estadistica General', 4),
    ('TS-APA', 3, 'Espanol I', 3),
    ('TS-APA', 3, 'Gestion de la Calidad', 3),
    ('TS-APA', 3, 'Etica Profesional', 2),
    ('TS-APA', 3, 'Filosofia', 3),
    ('TS-APA', 4, 'Presupuesto Empresarial', 3),
    ('TS-APA', 4, 'Responsabilidad Social Empresarial', 2),
    ('TS-APA', 4, 'Administracion Publica', 3),
    ('TS-APA', 4, 'Metodologia de la Investigacion', 3),
    ('TS-APA', 5, 'Espanol II', 3),
    ('TS-APA', 5, 'Emprendimiento', 3),
    ('TS-APA', 5, 'Ingles II', 3),
    ('TS-APA', 5, 'Negociacion y Resolucion de Conflictos', 3),
    ('TS-APA', 6, 'Liderazgo', 2),
    ('TS-APA', 6, 'Contabilidad II', 4),
    ('TS-APA', 6, 'Historia Dominicana', 3),
    ('TS-APA', 6, 'Redaccion Academica', 3),
    ('TS-APA', 7, 'Comercio Electronico', 3),
    ('TS-APA', 7, 'Mercadotecnia I', 4),
    ('TS-APA', 7, 'Gestion del Cambio', 3),
    ('TS-APA', 7, 'Toma de Decisiones Gerenciales', 4),
    ('TS-APA', 8, 'Cadena de Suministro', 4),
    ('TS-APA', 8, 'Gestion del Talento Humano', 4),
    ('TS-APA', 8, 'Comportamiento Organizacional', 3),
    ('TS-APA', 8, 'Gestion de Operaciones', 4),
    ('TS-APA', 9, 'Innovacion Empresarial', 3),
    ('TS-APA', 9, 'Comercio Internacional', 4),
    ('TS-APA', 9, 'Gestion de Riesgos', 3),
    ('TS-APA', 9, 'Seminario de Grado', 4),
    ('TS-APA', 10, 'Finanzas Corporativas', 4),
    ('TS-APA', 10, 'Economia Empresarial', 4),
    ('TS-APA', 10, 'Mercadotecnia II', 4),
    ('TS-APA', 10, 'Contabilidad I', 4),
    ('TS-APA', 11, 'Planificacion Estrategica', 4),
    ('TS-APA', 11, 'Auditoria Administrativa', 3),
    ('PUB', 1, 'Tipografia', 3),
    ('PUB', 1, 'Matematica Basica', 4),
    ('PUB', 1, 'Marketing Digital', 3),
    ('PUB', 1, 'Manejo de Redes Sociales', 3),
    ('PUB', 2, 'Sonido y Mezcla', 3),
    ('PUB', 2, 'Diseno Grafico I', 4),
    ('PUB', 2, 'Tecnologia de la Informacion', 3),
    ('PUB', 2, 'Publicidad I', 4),
    ('PUB', 3, 'Dibujo Artistico', 4),
    ('PUB', 3, 'Ilustracion Digital', 4),
    ('PUB', 3, 'Redaccion Academica', 3),
    ('PUB', 3, 'Comunicacion Digital', 4),
    ('PUB', 4, 'Animacion 3D', 4),
    ('PUB', 4, 'Liderazgo', 2),
    ('PUB', 4, 'Semiotica', 3),
    ('PUB', 4, 'Historia del Arte', 3),
    ('PUB', 5, 'Espanol I', 3),
    ('PUB', 5, 'Fotografia II', 4),
    ('PUB', 5, 'Portafolio Profesional', 4),
    ('PUB', 5, 'Branding', 3),
    ('PUB', 6, 'Emprendimiento', 3),
    ('PUB', 6, 'Ingles I', 3),
    ('PUB', 6, 'Guionismo', 3),
    ('PUB', 6, 'Produccion Audiovisual', 4),
    ('PUB', 7, 'Ingles II', 3),
    ('PUB', 7, 'Direccion de Arte', 4),
    ('PUB', 7, 'Etica Profesional', 2),
    ('PUB', 7, 'Medio Ambiente y Sociedad', 2),
    ('PUB', 8, 'Animacion 2D', 4),
    ('PUB', 8, 'Ingles III', 3),
    ('PUB', 8, 'Estadistica General', 4),
    ('PUB', 8, 'Edicion de Video', 4),
    ('PUB', 9, 'Historia Dominicana', 3),
    ('PUB', 9, 'Espanol II', 3),
    ('PUB', 9, 'Fotografia I', 4),
    ('PUB', 9, 'Filosofia', 3),
    ('PUB', 10, 'Produccion de Eventos', 3),
    ('PUB', 10, 'Metodologia de la Investigacion', 3),
    ('PUB', 10, 'Diseno Grafico II', 4),
    ('PUB', 10, 'Creatividad e Innovacion', 3),
    ('PUB', 11, 'Diseno Editorial', 4),
    ('PUB', 11, 'Publicidad II', 4),
    ('PUB', 11, 'Redaccion Periodistica', 4),
    ('PUB', 11, 'Estrategia de Contenidos', 3),
    ('PUB', 12, 'Teoria del Color', 3),
    ('LEA', 1, 'Economia Empresarial', 4),
    ('LEA', 1, 'Medio Ambiente y Sociedad', 2),
    ('LEA', 1, 'Espanol II', 3),
    ('LEA', 1, 'Ingles I', 3),
    ('LEA', 2, 'Finanzas Corporativas', 4),
    ('LEA', 2, 'Espanol I', 3),
    ('LEA', 2, 'Historia Dominicana', 3),
    ('LEA', 2, 'Ingles III', 3),
    ('LEA', 3, 'Filosofia', 3),
    ('LEA', 3, 'Ingles II', 3),
    ('LEA', 3, 'Comportamiento Organizacional', 3),
    ('LEA', 3, 'Presupuesto Empresarial', 3),
    ('LEA', 4, 'Tecnologia de la Informacion', 3),
    ('LEA', 4, 'Mercadotecnia II', 4),
    ('LEA', 4, 'Negociacion y Resolucion de Conflictos', 3),
    ('LEA', 4, 'Matematica Basica', 4),
    ('LEA', 5, 'Planificacion Estrategica', 4),
    ('LEA', 5, 'Mercadotecnia I', 4),
    ('LEA', 5, 'Gestion del Talento Humano', 4),
    ('LEA', 5, 'Estadistica General', 4),
    ('LEA', 6, 'Metodologia de la Investigacion', 3),
    ('LEA', 6, 'Gestion del Cambio', 3),
    ('LEA', 6, 'Redaccion Academica', 3),
    ('LEA', 6, 'Emprendimiento', 3),
    ('LEA', 7, 'Etica Profesional', 2),
    ('LEA', 7, 'Liderazgo', 2),
    ('LEA', 7, 'Gestion de la Calidad', 3),
    ('LEA', 7, 'Toma de Decisiones Gerenciales', 4),
    ('LEA', 8, 'Seminario de Grado', 4),
    ('LEA', 8, 'Gestion de Operaciones', 4),
    ('LEA', 8, 'Cadena de Suministro', 4),
    ('LEA', 8, 'Contabilidad I', 4),
    ('LEA', 9, 'Comercio Internacional', 4),
    ('LEA', 9, 'Auditoria Administrativa', 3),
    ('LEA', 9, 'Derecho Empresarial', 3),
    ('LEA', 9, 'Contabilidad II', 4),
    ('LEA', 10, 'Administracion de Empresas', 4),
    ('LEA', 10, 'Comercio Electronico', 3),
    ('LEA', 10, 'Responsabilidad Social Empresarial', 2),
    ('LEA', 10, 'Gestion de Riesgos', 3),
    ('LEA', 11, 'Innovacion Empresarial', 3),
    ('LEA', 11, 'Administracion Publica', 3),
    ('DIG', 1, 'Ingles I', 3),
    ('DIG', 1, 'Contabilidad II', 4),
    ('DIG', 1, 'Tecnologia de la Informacion', 3),
    ('DIG', 1, 'Espanol II', 3),
    ('DIG', 2, 'Administracion de Empresas', 4),
    ('DIG', 2, 'Gestion del Cambio', 3),
    ('DIG', 2, 'Innovacion Empresarial', 3),
    ('DIG', 2, 'Presupuesto Empresarial', 3),
    ('DIG', 3, 'Finanzas Corporativas', 4),
    ('DIG', 3, 'Medio Ambiente y Sociedad', 2),
    ('DIG', 3, 'Cadena de Suministro', 4),
    ('DIG', 3, 'Ingles III', 3),
    ('DIG', 4, 'Estadistica General', 4),
    ('DIG', 4, 'Planificacion Estrategica', 4),
    ('DIG', 4, 'Derecho Empresarial', 3),
    ('DIG', 4, 'Toma de Decisiones Gerenciales', 4),
    ('DIG', 5, 'Etica Profesional', 2),
    ('DIG', 5, 'Filosofia', 3),
    ('DIG', 5, 'Metodologia de la Investigacion', 3),
    ('DIG', 5, 'Contabilidad I', 4),
    ('DIG', 6, 'Matematica Basica', 4),
    ('DIG', 6, 'Responsabilidad Social Empresarial', 2),
    ('DIG', 6, 'Espanol I', 3),
    ('DIG', 6, 'Historia Dominicana', 3),
    ('DIG', 7, 'Gestion del Talento Humano', 4),
    ('DIG', 7, 'Negociacion y Resolucion de Conflictos', 3),
    ('DIG', 7, 'Gestion de la Calidad', 3),
    ('DIG', 7, 'Liderazgo', 2),
    ('DIG', 8, 'Mercadotecnia I', 4),
    ('DIG', 8, 'Redaccion Academica', 3),
    ('DIG', 8, 'Emprendimiento', 3),
    ('DIG', 8, 'Comercio Internacional', 4),
    ('DIG', 9, 'Auditoria Administrativa', 3),
    ('DIG', 9, 'Ingles II', 3),
    ('DIG', 9, 'Gestion de Operaciones', 4),
    ('DIG', 9, 'Gestion de Riesgos', 3),
    ('DIG', 10, 'Economia Empresarial', 4),
    ('DIG', 10, 'Administracion Publica', 3),
    ('DIG', 10, 'Mercadotecnia II', 4),
    ('DIG', 10, 'Comportamiento Organizacional', 3),
    ('DIG', 11, 'Comercio Electronico', 3),
    ('DIG', 11, 'Seminario de Grado', 4),
    ('DIN', 1, 'Mercadotecnia II', 4),
    ('DIN', 1, 'Comercio Electronico', 3),
    ('DIN', 1, 'Presupuesto Empresarial', 3),
    ('DIN', 1, 'Gestion del Cambio', 3),
    ('DIN', 2, 'Espanol I', 3),
    ('DIN', 2, 'Ingles III', 3),
    ('DIN', 2, 'Matematica Basica', 4),
    ('DIN', 2, 'Toma de Decisiones Gerenciales', 4),
    ('DIN', 3, 'Filosofia', 3),
    ('DIN', 3, 'Innovacion Empresarial', 3),
    ('DIN', 3, 'Gestion de la Calidad', 3),
    ('DIN', 3, 'Medio Ambiente y Sociedad', 2),
    ('DIN', 4, 'Planificacion Estrategica', 4),
    ('DIN', 4, 'Espanol II', 3),
    ('DIN', 4, 'Emprendimiento', 3),
    ('DIN', 4, 'Redaccion Academica', 3),
    ('DIN', 5, 'Metodologia de la Investigacion', 3),
    ('DIN', 5, 'Liderazgo', 2),
    ('DIN', 5, 'Gestion del Talento Humano', 4),
    ('DIN', 5, 'Historia Dominicana', 3),
    ('DIN', 6, 'Comportamiento Organizacional', 3),
    ('DIN', 6, 'Ingles I', 3),
    ('DIN', 6, 'Etica Profesional', 2),
    ('DIN', 6, 'Estadistica General', 4),
    ('DIN', 7, 'Ingles II', 3),
    ('DIN', 7, 'Tecnologia de la Informacion', 3),
    ('DIN', 7, 'Responsabilidad Social Empresarial', 2),
    ('DIN', 7, 'Negociacion y Resolucion de Conflictos', 3),
    ('DIN', 8, 'Contabilidad II', 4),
    ('DIN', 8, 'Contabilidad I', 4),
    ('DIN', 8, 'Comercio Internacional', 4),
    ('DIN', 8, 'Gestion de Operaciones', 4),
    ('DIN', 9, 'Administracion de Empresas', 4),
    ('DIN', 9, 'Finanzas Corporativas', 4),
    ('DIN', 9, 'Gestion de Riesgos', 3),
    ('DIN', 9, 'Derecho Empresarial', 3),
    ('DIN', 10, 'Cadena de Suministro', 4),
    ('DIN', 10, 'Economia Empresarial', 4),
    ('DIN', 10, 'Mercadotecnia I', 4),
    ('DIN', 10, 'Auditoria Administrativa', 3),
    ('DIN', 11, 'Administracion Publica', 3),
    ('DIN', 11, 'Seminario de Grado', 4),
    ('CPM', 1, 'Ingles III', 3),
    ('CPM', 1, 'Estadistica General', 4),
    ('CPM', 1, 'Comercio Electronico', 3),
    ('CPM', 1, 'Matematica Basica', 4),
    ('CPM', 2, 'Seminario de Grado', 4),
    ('CPM', 2, 'Espanol II', 3),
    ('CPM', 2, 'Metodologia de la Investigacion', 3),
    ('CPM', 2, 'Historia Dominicana', 3),
    ('CPM', 3, 'Ingles I', 3),
    ('CPM', 3, 'Economia Empresarial', 4),
    ('CPM', 3, 'Gestion de Operaciones', 4),
    ('CPM', 3, 'Redaccion Academica', 3),
    ('CPM', 4, 'Contabilidad II', 4),
    ('CPM', 4, 'Gestion del Talento Humano', 4),
    ('CPM', 4, 'Gestion del Cambio', 3),
    ('CPM', 4, 'Liderazgo', 2),
    ('CPM', 5, 'Toma de Decisiones Gerenciales', 4),
    ('CPM', 5, 'Espanol I', 3),
    ('CPM', 5, 'Medio Ambiente y Sociedad', 2),
    ('CPM', 5, 'Presupuesto Empresarial', 3),
    ('CPM', 6, 'Tecnologia de la Informacion', 3),
    ('CPM', 6, 'Emprendimiento', 3),
    ('CPM', 6, 'Auditoria Administrativa', 3),
    ('CPM', 6, 'Mercadotecnia II', 4),
    ('CPM', 7, 'Gestion de Riesgos', 3),
    ('CPM', 7, 'Comportamiento Organizacional', 3),
    ('CPM', 7, 'Filosofia', 3),
    ('CPM', 7, 'Ingles II', 3),
    ('CPM', 8, 'Etica Profesional', 2),
    ('CPM', 8, 'Innovacion Empresarial', 3),
    ('CPM', 8, 'Planificacion Estrategica', 4),
    ('CPM', 8, 'Administracion Publica', 3),
    ('CPM', 9, 'Negociacion y Resolucion de Conflictos', 3),
    ('CPM', 9, 'Comercio Internacional', 4),
    ('CPM', 9, 'Administracion de Empresas', 4),
    ('CPM', 9, 'Derecho Empresarial', 3),
    ('CPM', 10, 'Finanzas Corporativas', 4),
    ('CPM', 10, 'Contabilidad I', 4),
    ('CPM', 10, 'Gestion de la Calidad', 3),
    ('CPM', 10, 'Cadena de Suministro', 4),
    ('CPM', 11, 'Responsabilidad Social Empresarial', 2),
    ('CPM', 11, 'Mercadotecnia I', 4),
    ('CDG', 1, 'Estadistica General', 4),
    ('CDG', 1, 'Cadena de Suministro', 4),
    ('CDG', 1, 'Espanol II', 3),
    ('CDG', 1, 'Presupuesto Empresarial', 3),
    ('CDG', 2, 'Ingles II', 3),
    ('CDG', 2, 'Responsabilidad Social Empresarial', 2),
    ('CDG', 2, 'Mercadotecnia II', 4),
    ('CDG', 2, 'Auditoria Administrativa', 3),
    ('CDG', 3, 'Derecho Empresarial', 3),
    ('CDG', 3, 'Toma de Decisiones Gerenciales', 4),
    ('CDG', 3, 'Ingles I', 3),
    ('CDG', 3, 'Filosofia', 3),
    ('CDG', 4, 'Etica Profesional', 2),
    ('CDG', 4, 'Redaccion Academica', 3),
    ('CDG', 4, 'Administracion Publica', 3),
    ('CDG', 4, 'Ingles III', 3),
    ('CDG', 5, 'Espanol I', 3),
    ('CDG', 5, 'Historia Dominicana', 3),
    ('CDG', 5, 'Mercadotecnia I', 4),
    ('CDG', 5, 'Seminario de Grado', 4),
    ('CDG', 6, 'Metodologia de la Investigacion', 3),
    ('CDG', 6, 'Gestion de Operaciones', 4),
    ('CDG', 6, 'Medio Ambiente y Sociedad', 2),
    ('CDG', 6, 'Negociacion y Resolucion de Conflictos', 3),
    ('CDG', 7, 'Administracion de Empresas', 4),
    ('CDG', 7, 'Gestion de la Calidad', 3),
    ('CDG', 7, 'Matematica Basica', 4),
    ('CDG', 7, 'Tecnologia de la Informacion', 3),
    ('CDG', 8, 'Emprendimiento', 3),
    ('CDG', 8, 'Liderazgo', 2),
    ('CDG', 8, 'Planificacion Estrategica', 4),
    ('CDG', 8, 'Comercio Internacional', 4),
    ('CDG', 9, 'Economia Empresarial', 4),
    ('CDG', 9, 'Innovacion Empresarial', 3),
    ('CDG', 9, 'Finanzas Corporativas', 4),
    ('CDG', 9, 'Contabilidad II', 4),
    ('CDG', 10, 'Gestion del Cambio', 3),
    ('CDG', 10, 'Comportamiento Organizacional', 3),
    ('CDG', 10, 'Comercio Electronico', 3),
    ('CDG', 10, 'Contabilidad I', 4),
    ('CDG', 11, 'Gestion del Talento Humano', 4),
    ('CDG', 11, 'Gestion de Riesgos', 3),
    ('CIN', 1, 'Ingles III', 3),
    ('CIN', 1, 'Medio Ambiente y Sociedad', 2),
    ('CIN', 1, 'Emprendimiento', 3),
    ('CIN', 1, 'Tipografia', 3),
    ('CIN', 2, 'Ingles I', 3),
    ('CIN', 2, 'Metodologia de la Investigacion', 3),
    ('CIN', 2, 'Ilustracion Digital', 4),
    ('CIN', 2, 'Dibujo Artistico', 4),
    ('CIN', 3, 'Direccion de Arte', 4),
    ('CIN', 3, 'Historia Dominicana', 3),
    ('CIN', 3, 'Sonido y Mezcla', 3),
    ('CIN', 3, 'Diseno Editorial', 4),
    ('CIN', 4, 'Portafolio Profesional', 4),
    ('CIN', 4, 'Comunicacion Digital', 4),
    ('CIN', 4, 'Publicidad I', 4),
    ('CIN', 4, 'Ingles II', 3),
    ('CIN', 5, 'Espanol II', 3),
    ('CIN', 5, 'Etica Profesional', 2),
    ('CIN', 5, 'Tecnologia de la Informacion', 3),
    ('CIN', 5, 'Semiotica', 3),
    ('CIN', 6, 'Branding', 3),
    ('CIN', 6, 'Estadistica General', 4),
    ('CIN', 6, 'Historia del Arte', 3),
    ('CIN', 6, 'Produccion de Eventos', 3),
    ('CIN', 7, 'Redaccion Academica', 3),
    ('CIN', 7, 'Fotografia II', 4),
    ('CIN', 7, 'Guionismo', 3),
    ('CIN', 7, 'Animacion 2D', 4),
    ('CIN', 8, 'Liderazgo', 2),
    ('CIN', 8, 'Filosofia', 3),
    ('CIN', 8, 'Matematica Basica', 4),
    ('CIN', 8, 'Redaccion Periodistica', 4),
    ('CIN', 9, 'Espanol I', 3),
    ('CIN', 9, 'Fotografia I', 4),
    ('CIN', 9, 'Produccion Audiovisual', 4),
    ('CIN', 9, 'Manejo de Redes Sociales', 3),
    ('CIN', 10, 'Publicidad II', 4),
    ('CIN', 10, 'Diseno Grafico II', 4),
    ('CIN', 10, 'Animacion 3D', 4),
    ('CIN', 10, 'Diseno Grafico I', 4),
    ('CIN', 11, 'Creatividad e Innovacion', 3),
    ('CIN', 11, 'Estrategia de Contenidos', 3),
    ('CIN', 11, 'Marketing Digital', 3),
    ('CIN', 11, 'Teoria del Color', 3),
    ('CIN', 12, 'Edicion de Video', 4),
    ('PSO', 1, 'Ingles II', 3),
    ('PSO', 1, 'Ingles III', 3),
    ('PSO', 1, 'Contabilidad II', 4),
    ('PSO', 1, 'Administracion Publica', 3),
    ('PSO', 2, 'Matematica Basica', 4),
    ('PSO', 2, 'Liderazgo', 2),
    ('PSO', 2, 'Emprendimiento', 3),
    ('PSO', 2, 'Espanol II', 3),
    ('PSO', 3, 'Espanol I', 3),
    ('PSO', 3, 'Gestion del Cambio', 3),
    ('PSO', 3, 'Comercio Electronico', 3),
    ('PSO', 3, 'Redaccion Academica', 3),
    ('PSO', 4, 'Historia Dominicana', 3),
    ('PSO', 4, 'Mercadotecnia I', 4),
    ('PSO', 4, 'Ingles I', 3),
    ('PSO', 4, 'Administracion de Empresas', 4),
    ('PSO', 5, 'Finanzas Corporativas', 4),
    ('PSO', 5, 'Medio Ambiente y Sociedad', 2),
    ('PSO', 5, 'Economia Empresarial', 4),
    ('PSO', 5, 'Gestion de Operaciones', 4),
    ('PSO', 6, 'Derecho Empresarial', 3),
    ('PSO', 6, 'Tecnologia de la Informacion', 3),
    ('PSO', 6, 'Innovacion Empresarial', 3),
    ('PSO', 6, 'Filosofia', 3),
    ('PSO', 7, 'Mercadotecnia II', 4),
    ('PSO', 7, 'Estadistica General', 4),
    ('PSO', 7, 'Etica Profesional', 2),
    ('PSO', 7, 'Contabilidad I', 4),
    ('PSO', 8, 'Gestion de Riesgos', 3),
    ('PSO', 8, 'Metodologia de la Investigacion', 3),
    ('PSO', 8, 'Toma de Decisiones Gerenciales', 4),
    ('PSO', 8, 'Seminario de Grado', 4),
    ('PSO', 9, 'Comportamiento Organizacional', 3),
    ('PSO', 9, 'Comercio Internacional', 4),
    ('PSO', 9, 'Presupuesto Empresarial', 3),
    ('PSO', 9, 'Gestion de la Calidad', 3),
    ('PSO', 10, 'Negociacion y Resolucion de Conflictos', 3),
    ('PSO', 10, 'Cadena de Suministro', 4),
    ('PSO', 10, 'Auditoria Administrativa', 3),
    ('PSO', 10, 'Responsabilidad Social Empresarial', 2),
    ('PSO', 11, 'Gestion del Talento Humano', 4),
    ('PSO', 11, 'Planificacion Estrategica', 4),
    ('TS-FIN', 1, 'Metodologia de la Investigacion', 3),
    ('TS-FIN', 1, 'Contabilidad de Costos', 4),
    ('TS-FIN', 1, 'Liderazgo', 2),
    ('TS-FIN', 1, 'Estadistica General', 4),
    ('TS-FIN', 2, 'Medio Ambiente y Sociedad', 2),
    ('TS-FIN', 2, 'Emprendimiento', 3),
    ('TS-FIN', 2, 'Finanzas Internacionales', 4),
    ('TS-FIN', 2, 'Ingles III', 3),
    ('TS-FIN', 3, 'Espanol II', 3),
    ('TS-FIN', 3, 'Matematica Basica', 4),
    ('TS-FIN', 3, 'Etica Profesional', 2),
    ('TS-FIN', 3, 'Sistemas Contables', 3),
    ('TS-FIN', 4, 'Filosofia', 3),
    ('TS-FIN', 4, 'Ingles I', 3),
    ('TS-FIN', 4, 'Auditoria I', 4),
    ('TS-FIN', 4, 'Espanol I', 3),
    ('TS-FIN', 5, 'Ingles II', 3),
    ('TS-FIN', 5, 'Redaccion Academica', 3),
    ('TS-FIN', 5, 'Impuestos', 4),
    ('TS-FIN', 5, 'Historia Dominicana', 3),
    ('TS-FIN', 6, 'Tecnologia de la Informacion', 3),
    ('TS-FIN', 6, 'Contabilidad II', 4),
    ('TS-FIN', 6, 'Derecho Tributario', 4),
    ('TS-FIN', 6, 'Economia Monetaria', 3),
    ('TS-FIN', 7, 'Control Interno', 3),
    ('TS-FIN', 7, 'Matematica Financiera', 4),
    ('TS-FIN', 7, 'Banca y Seguros', 3),
    ('TS-FIN', 7, 'Formulacion de Proyectos', 4),
    ('TS-FIN', 8, 'Macroeconomia', 3),
    ('TS-FIN', 8, 'Econometria', 4),
    ('TS-FIN', 8, 'Contabilidad I', 4),
    ('TS-FIN', 8, 'Auditoria II', 4),
    ('TS-FIN', 9, 'Contabilidad Gubernamental', 3),
    ('TS-FIN', 9, 'Microeconomia', 3),
    ('TS-FIN', 9, 'Mercado de Capitales', 4),
    ('TS-FIN', 9, 'Portafolios de Inversion', 4),
    ('TS-FIN', 10, 'Normas Internacionales de Contabilidad', 4),
    ('TS-FIN', 10, 'Finanzas Corporativas', 4),
    ('TS-FIN', 10, 'Contabilidad III', 4),
    ('TS-FIN', 10, 'Etica en los Negocios', 2),
    ('TS-FIN', 11, 'Analisis Financiero', 4),
    ('TS-FIN', 11, 'Valoracion de Empresas', 4),
    ('TS-CE', 1, 'Redaccion Academica', 3),
    ('TS-CE', 1, 'Finanzas Internacionales', 4),
    ('TS-CE', 1, 'Ingles I', 3),
    ('TS-CE', 1, 'Tecnologia de la Informacion', 3),
    ('TS-CE', 2, 'Estadistica General', 4),
    ('TS-CE', 2, 'Metodologia de la Investigacion', 3),
    ('TS-CE', 2, 'Normas Internacionales de Contabilidad', 4),
    ('TS-CE', 2, 'Contabilidad II', 4),
    ('TS-CE', 3, 'Valoracion de Empresas', 4),
    ('TS-CE', 3, 'Historia Dominicana', 3),
    ('TS-CE', 3, 'Ingles III', 3),
    ('TS-CE', 3, 'Liderazgo', 2),
    ('TS-CE', 4, 'Espanol I', 3),
    ('TS-CE', 4, 'Matematica Basica', 4),
    ('TS-CE', 4, 'Medio Ambiente y Sociedad', 2),
    ('TS-CE', 4, 'Microeconomia', 3),
    ('TS-CE', 5, 'Emprendimiento', 3),
    ('TS-CE', 5, 'Derecho Tributario', 4),
    ('TS-CE', 5, 'Mercado de Capitales', 4),
    ('TS-CE', 5, 'Filosofia', 3),
    ('TS-CE', 6, 'Espanol II', 3),
    ('TS-CE', 6, 'Etica Profesional', 2),
    ('TS-CE', 6, 'Ingles II', 3),
    ('TS-CE', 6, 'Portafolios de Inversion', 4),
    ('TS-CE', 7, 'Auditoria I', 4),
    ('TS-CE', 7, 'Formulacion de Proyectos', 4),
    ('TS-CE', 7, 'Control Interno', 3),
    ('TS-CE', 7, 'Etica en los Negocios', 2),
    ('TS-CE', 8, 'Macroeconomia', 3),
    ('TS-CE', 8, 'Contabilidad Gubernamental', 3),
    ('TS-CE', 8, 'Impuestos', 4),
    ('TS-CE', 8, 'Economia Monetaria', 3),
    ('TS-CE', 9, 'Analisis Financiero', 4),
    ('TS-CE', 9, 'Auditoria II', 4),
    ('TS-CE', 9, 'Econometria', 4),
    ('TS-CE', 9, 'Matematica Financiera', 4),
    ('TS-CE', 10, 'Contabilidad III', 4),
    ('TS-CE', 10, 'Banca y Seguros', 3),
    ('TS-CE', 10, 'Sistemas Contables', 3),
    ('TS-CE', 10, 'Finanzas Corporativas', 4),
    ('TS-CE', 11, 'Contabilidad I', 4),
    ('TS-CE', 11, 'Contabilidad de Costos', 4),
    ('FIN', 1, 'Normas Internacionales de Contabilidad', 4),
    ('FIN', 1, 'Matematica Financiera', 4),
    ('FIN', 1, 'Ingles II', 3),
    ('FIN', 1, 'Auditoria II', 4),
    ('FIN', 2, 'Derecho Tributario', 4),
    ('FIN', 2, 'Redaccion Academica', 3),
    ('FIN', 2, 'Etica Profesional', 2),
    ('FIN', 2, 'Espanol II', 3),
    ('FIN', 3, 'Microeconomia', 3),
    ('FIN', 3, 'Metodologia de la Investigacion', 3),
    ('FIN', 3, 'Econometria', 4),
    ('FIN', 3, 'Analisis Financiero', 4),
    ('FIN', 4, 'Finanzas Internacionales', 4),
    ('FIN', 4, 'Ingles I', 3),
    ('FIN', 4, 'Matematica Basica', 4),
    ('FIN', 4, 'Historia Dominicana', 3),
    ('FIN', 5, 'Economia Monetaria', 3),
    ('FIN', 5, 'Ingles III', 3),
    ('FIN', 5, 'Contabilidad III', 4),
    ('FIN', 5, 'Filosofia', 3),
    ('FIN', 6, 'Macroeconomia', 3),
    ('FIN', 6, 'Contabilidad Gubernamental', 3),
    ('FIN', 6, 'Liderazgo', 2),
    ('FIN', 6, 'Espanol I', 3),
    ('FIN', 7, 'Medio Ambiente y Sociedad', 2),
    ('FIN', 7, 'Emprendimiento', 3),
    ('FIN', 7, 'Banca y Seguros', 3),
    ('FIN', 7, 'Estadistica General', 4),
    ('FIN', 8, 'Contabilidad de Costos', 4),
    ('FIN', 8, 'Tecnologia de la Informacion', 3),
    ('FIN', 8, 'Sistemas Contables', 3),
    ('FIN', 8, 'Contabilidad I', 4),
    ('FIN', 9, 'Mercado de Capitales', 4),
    ('FIN', 9, 'Contabilidad II', 4),
    ('FIN', 9, 'Etica en los Negocios', 2),
    ('FIN', 9, 'Finanzas Corporativas', 4),
    ('FIN', 10, 'Valoracion de Empresas', 4),
    ('FIN', 10, 'Control Interno', 3),
    ('FIN', 10, 'Portafolios de Inversion', 4),
    ('FIN', 10, 'Formulacion de Proyectos', 4),
    ('FIN', 11, 'Impuestos', 4),
    ('FIN', 11, 'Auditoria I', 4),
    ('ECO', 1, 'Gestion del Talento Humano', 4),
    ('ECO', 1, 'Historia Dominicana', 3),
    ('ECO', 1, 'Gestion del Cambio', 3),
    ('ECO', 1, 'Ingles III', 3),
    ('ECO', 2, 'Etica Profesional', 2),
    ('ECO', 2, 'Comercio Internacional', 4),
    ('ECO', 2, 'Gestion de la Calidad', 3),
    ('ECO', 2, 'Comercio Electronico', 3),
    ('ECO', 3, 'Medio Ambiente y Sociedad', 2),
    ('ECO', 3, 'Emprendimiento', 3),
    ('ECO', 3, 'Tecnologia de la Informacion', 3),
    ('ECO', 3, 'Liderazgo', 2),
    ('ECO', 4, 'Planificacion Estrategica', 4),
    ('ECO', 4, 'Derecho Empresarial', 3),
    ('ECO', 4, 'Gestion de Riesgos', 3),
    ('ECO', 4, 'Filosofia', 3),
    ('ECO', 5, 'Espanol I', 3),
    ('ECO', 5, 'Negociacion y Resolucion de Conflictos', 3),
    ('ECO', 5, 'Estadistica General', 4),
    ('ECO', 5, 'Cadena de Suministro', 4),
    ('ECO', 6, 'Economia Empresarial', 4),
    ('ECO', 6, 'Gestion de Operaciones', 4),
    ('ECO', 6, 'Metodologia de la Investigacion', 3),
    ('ECO', 6, 'Responsabilidad Social Empresarial', 2),
    ('ECO', 7, 'Ingles I', 3),
    ('ECO', 7, 'Ingles II', 3),
    ('ECO', 7, 'Matematica Basica', 4),
    ('ECO', 7, 'Contabilidad I', 4),
    ('ECO', 8, 'Presupuesto Empresarial', 3),
    ('ECO', 8, 'Redaccion Academica', 3),
    ('ECO', 8, 'Espanol II', 3),
    ('ECO', 8, 'Administracion de Empresas', 4),
    ('ECO', 9, 'Comportamiento Organizacional', 3),
    ('ECO', 9, 'Mercadotecnia II', 4),
    ('ECO', 9, 'Mercadotecnia I', 4),
    ('ECO', 9, 'Toma de Decisiones Gerenciales', 4),
    ('ECO', 10, 'Auditoria Administrativa', 3),
    ('ECO', 10, 'Administracion Publica', 3),
    ('ECO', 10, 'Contabilidad II', 4),
    ('ECO', 10, 'Finanzas Corporativas', 4),
    ('ECO', 11, 'Innovacion Empresarial', 3),
    ('ECO', 11, 'Seminario de Grado', 4),
    ('CON', 1, 'Espanol I', 3),
    ('CON', 1, 'Etica en los Negocios', 2),
    ('CON', 1, 'Microeconomia', 3),
    ('CON', 1, 'Ingles I', 3),
    ('CON', 2, 'Contabilidad II', 4),
    ('CON', 2, 'Mercado de Capitales', 4),
    ('CON', 2, 'Contabilidad I', 4),
    ('CON', 2, 'Emprendimiento', 3),
    ('CON', 3, 'Metodologia de la Investigacion', 3),
    ('CON', 3, 'Normas Internacionales de Contabilidad', 4),
    ('CON', 3, 'Auditoria I', 4),
    ('CON', 3, 'Control Interno', 3),
    ('CON', 4, 'Economia Monetaria', 3),
    ('CON', 4, 'Historia Dominicana', 3),
    ('CON', 4, 'Ingles II', 3),
    ('CON', 4, 'Ingles III', 3),
    ('CON', 5, 'Matematica Financiera', 4),
    ('CON', 5, 'Finanzas Corporativas', 4),
    ('CON', 5, 'Derecho Tributario', 4),
    ('CON', 5, 'Contabilidad de Costos', 4),
    ('CON', 6, 'Impuestos', 4),
    ('CON', 6, 'Analisis Financiero', 4),
    ('CON', 6, 'Medio Ambiente y Sociedad', 2),
    ('CON', 6, 'Contabilidad Gubernamental', 3),
    ('CON', 7, 'Formulacion de Proyectos', 4),
    ('CON', 7, 'Espanol II', 3),
    ('CON', 7, 'Tecnologia de la Informacion', 3),
    ('CON', 7, 'Valoracion de Empresas', 4),
    ('CON', 8, 'Estadistica General', 4),
    ('CON', 8, 'Contabilidad III', 4),
    ('CON', 8, 'Econometria', 4),
    ('CON', 8, 'Portafolios de Inversion', 4),
    ('CON', 9, 'Matematica Basica', 4),
    ('CON', 9, 'Banca y Seguros', 3),
    ('CON', 9, 'Liderazgo', 2),
    ('CON', 9, 'Sistemas Contables', 3),
    ('CON', 10, 'Etica Profesional', 2),
    ('CON', 10, 'Auditoria II', 4),
    ('CON', 10, 'Redaccion Academica', 3),
    ('CON', 10, 'Finanzas Internacionales', 4),
    ('CON', 11, 'Macroeconomia', 3),
    ('CON', 11, 'Filosofia', 3),
    ('TS-GL', 1, 'Derecho Laboral', 4),
    ('TS-GL', 1, 'Espanol II', 3),
    ('TS-GL', 1, 'Derecho de Familia', 3),
    ('TS-GL', 1, 'Derecho Notarial', 3),
    ('TS-GL', 2, 'Argumentacion Juridica', 3),
    ('TS-GL', 2, 'Emprendimiento', 3),
    ('TS-GL', 2, 'Liderazgo', 2),
    ('TS-GL', 2, 'Historia Dominicana', 3),
    ('TS-GL', 3, 'Matematica Basica', 4),
    ('TS-GL', 3, 'Ingles II', 3),
    ('TS-GL', 3, 'Filosofia', 3),
    ('TS-GL', 3, 'Derechos Humanos', 3),
    ('TS-GL', 4, 'Tecnologia de la Informacion', 3),
    ('TS-GL', 4, 'Metodologia de la Investigacion', 3),
    ('TS-GL', 4, 'Derecho Constitucional', 4),
    ('TS-GL', 4, 'Criminalistica', 4),
    ('TS-GL', 5, 'Medicina Legal', 3),
    ('TS-GL', 5, 'Espanol I', 3),
    ('TS-GL', 5, 'Derecho Civil II', 4),
    ('TS-GL', 5, 'Medio Ambiente y Sociedad', 2),
    ('TS-GL', 6, 'Ingles I', 3),
    ('TS-GL', 6, 'Introduccion al Derecho', 4),
    ('TS-GL', 6, 'Estadistica General', 4),
    ('TS-GL', 6, 'Redaccion Academica', 3),
    ('TS-GL', 7, 'Etica Profesional', 2),
    ('TS-GL', 7, 'Derecho Administrativo', 4),
    ('TS-GL', 7, 'Ingles III', 3),
    ('TS-GL', 7, 'Derecho Penal I', 4),
    ('TS-GL', 8, 'Derecho Internacional Publico', 4),
    ('TS-GL', 8, 'Derecho de Propiedad Intelectual', 3),
    ('TS-GL', 8, 'Derecho Procesal Penal', 4),
    ('TS-GL', 8, 'Derecho Penal II', 4),
    ('TS-GL', 9, 'Derecho Procesal Civil', 4),
    ('TS-GL', 9, 'Deontologia Juridica', 2),
    ('TS-GL', 9, 'Conciliacion y Arbitraje', 3),
    ('TS-GL', 9, 'Derecho Ambiental', 3),
    ('TS-GL', 10, 'Derecho Comercial', 4),
    ('TS-GL', 10, 'Derecho Electoral', 3),
    ('TS-GL', 10, 'Litigacion Oral', 4),
    ('TS-GL', 10, 'Derecho Tributario', 4),
    ('TS-GL', 11, 'Derecho Civil I', 4),
    ('TS-GL', 11, 'Derecho Internacional Privado', 4),
    ('TS-CRI', 1, 'Negociacion y Resolucion de Conflictos', 3),
    ('TS-CRI', 1, 'Ingles III', 3),
    ('TS-CRI', 1, 'Estadistica General', 4),
    ('TS-CRI', 1, 'Tecnologia de la Informacion', 3),
    ('TS-CRI', 2, 'Auditoria Administrativa', 3),
    ('TS-CRI', 2, 'Presupuesto Empresarial', 3),
    ('TS-CRI', 2, 'Comportamiento Organizacional', 3),
    ('TS-CRI', 2, 'Responsabilidad Social Empresarial', 2),
    ('TS-CRI', 3, 'Filosofia', 3),
    ('TS-CRI', 3, 'Seminario de Grado', 4),
    ('TS-CRI', 3, 'Espanol I', 3),
    ('TS-CRI', 3, 'Gestion del Talento Humano', 4),
    ('TS-CRI', 4, 'Ingles I', 3),
    ('TS-CRI', 4, 'Finanzas Corporativas', 4),
    ('TS-CRI', 4, 'Contabilidad II', 4),
    ('TS-CRI', 4, 'Emprendimiento', 3),
    ('TS-CRI', 5, 'Administracion Publica', 3),
    ('TS-CRI', 5, 'Historia Dominicana', 3),
    ('TS-CRI', 5, 'Liderazgo', 2),
    ('TS-CRI', 5, 'Gestion de la Calidad', 3),
    ('TS-CRI', 6, 'Ingles II', 3),
    ('TS-CRI', 6, 'Espanol II', 3),
    ('TS-CRI', 6, 'Redaccion Academica', 3),
    ('TS-CRI', 6, 'Etica Profesional', 2),
    ('TS-CRI', 7, 'Mercadotecnia II', 4),
    ('TS-CRI', 7, 'Metodologia de la Investigacion', 3),
    ('TS-CRI', 7, 'Medio Ambiente y Sociedad', 2),
    ('TS-CRI', 7, 'Comercio Electronico', 3),
    ('TS-CRI', 8, 'Contabilidad I', 4),
    ('TS-CRI', 8, 'Innovacion Empresarial', 3),
    ('TS-CRI', 8, 'Matematica Basica', 4),
    ('TS-CRI', 8, 'Mercadotecnia I', 4),
    ('TS-CRI', 9, 'Gestion de Operaciones', 4),
    ('TS-CRI', 9, 'Cadena de Suministro', 4),
    ('TS-CRI', 9, 'Comercio Internacional', 4),
    ('TS-CRI', 9, 'Toma de Decisiones Gerenciales', 4),
    ('TS-CRI', 10, 'Gestion del Cambio', 3),
    ('TS-CRI', 10, 'Administracion de Empresas', 4),
    ('TS-CRI', 10, 'Planificacion Estrategica', 4),
    ('TS-CRI', 10, 'Economia Empresarial', 4),
    ('TS-CRI', 11, 'Gestion de Riesgos', 3),
    ('TS-CRI', 11, 'Derecho Empresarial', 3),
    ('DER', 1, 'Derecho Civil II', 4),
    ('DER', 1, 'Espanol I', 3),
    ('DER', 1, 'Derecho Penal I', 4),
    ('DER', 1, 'Etica Profesional', 2),
    ('DER', 2, 'Espanol II', 3),
    ('DER', 2, 'Metodologia de la Investigacion', 3),
    ('DER', 2, 'Derecho Internacional Publico', 4),
    ('DER', 2, 'Tecnologia de la Informacion', 3),
    ('DER', 3, 'Liderazgo', 2),
    ('DER', 3, 'Matematica Basica', 4),
    ('DER', 3, 'Estadistica General', 4),
    ('DER', 3, 'Derecho Comercial', 4),
    ('DER', 4, 'Derecho de Propiedad Intelectual', 3),
    ('DER', 4, 'Derecho de Familia', 3),
    ('DER', 4, 'Emprendimiento', 3),
    ('DER', 4, 'Introduccion al Derecho', 4),
    ('DER', 5, 'Medio Ambiente y Sociedad', 2),
    ('DER', 5, 'Medicina Legal', 3),
    ('DER', 5, 'Ingles I', 3),
    ('DER', 5, 'Derecho Procesal Penal', 4),
    ('DER', 6, 'Ingles II', 3),
    ('DER', 6, 'Filosofia', 3),
    ('DER', 6, 'Historia Dominicana', 3),
    ('DER', 6, 'Redaccion Academica', 3),
    ('DER', 7, 'Ingles III', 3),
    ('DER', 7, 'Argumentacion Juridica', 3),
    ('DER', 7, 'Litigacion Oral', 4),
    ('DER', 7, 'Conciliacion y Arbitraje', 3),
    ('DER', 8, 'Derecho Constitucional', 4),
    ('DER', 8, 'Deontologia Juridica', 2),
    ('DER', 8, 'Criminalistica', 4),
    ('DER', 8, 'Derecho Notarial', 3),
    ('DER', 9, 'Derecho Civil I', 4),
    ('DER', 9, 'Derecho Laboral', 4),
    ('DER', 9, 'Derecho Penal II', 4),
    ('DER', 9, 'Derechos Humanos', 3),
    ('DER', 10, 'Derecho Ambiental', 3),
    ('DER', 10, 'Derecho Electoral', 3),
    ('DER', 10, 'Derecho Tributario', 4),
    ('DER', 10, 'Derecho Internacional Privado', 4),
    ('DER', 11, 'Derecho Administrativo', 4),
    ('DER', 11, 'Derecho Procesal Civil', 4),
    ('LEL', 1, 'Etica Profesional', 2),
    ('LEL', 1, 'Historia Dominicana', 3),
    ('LEL', 1, 'Liderazgo', 2),
    ('LEL', 1, 'Estadistica General', 4),
    ('LEL', 2, 'Redaccion Academica', 4),
    ('LEL', 2, 'Tecnologia de la Informacion', 3),
    ('LEL', 2, 'Practica Docente Lengua II', 5),
    ('LEL', 2, 'Literatura Caribena', 4),
    ('LEL', 3, 'Correccion de Estilo', 3),
    ('LEL', 3, 'Literatura Dominicana', 4),
    ('LEL', 3, 'Metodologia de la Investigacion', 3),
    ('LEL', 3, 'Matematica Basica', 4),
    ('LEL', 4, 'Medio Ambiente y Sociedad', 2),
    ('LEL', 4, 'Morfosintaxis I', 4),
    ('LEL', 4, 'Oratoria', 3),
    ('LEL', 4, 'Literatura Universal', 4),
    ('LEL', 5, 'Analisis del Discurso', 3),
    ('LEL', 5, 'Ingles I', 3),
    ('LEL', 5, 'Fonetica y Fonologia', 4),
    ('LEL', 5, 'Critica Literaria', 3),
    ('LEL', 6, 'Filosofia', 3),
    ('LEL', 6, 'Sociolinguistica', 3),
    ('LEL', 6, 'Literatura Espanola', 4),
    ('LEL', 6, 'Emprendimiento', 3),
    ('LEL', 7, 'Taller de Creacion Literaria', 3),
    ('LEL', 7, 'Espanol I', 3),
    ('LEL', 7, 'Pragmatica', 3),
    ('LEL', 7, 'Semantica', 3),
    ('LEL', 8, 'Literatura Hispanoamericana', 4),
    ('LEL', 8, 'Gramatica Espanola', 4),
    ('LEL', 8, 'Practica Docente Lengua I', 4),
    ('LEL', 8, 'Espanol II', 3),
    ('LEL', 9, 'Ingles III', 3),
    ('LEL', 9, 'Redaccion Academica', 3),
    ('LEL', 9, 'Didactica de la Lengua', 4),
    ('LEL', 9, 'Ingles II', 3),
    ('LEL', 10, 'Morfosintaxis II', 4),
    ('LEL', 10, 'Linguistica General', 4),
    ('LEL', 10, 'Psicolinguistica', 3),
    ('LEL', 10, 'Lexicografia', 3),
    ('LEL', 11, 'Dialectologia', 3),
    ('LEL', 11, 'Teoria Literaria', 4),
    ('LEI', 1, 'Medio Ambiente y Sociedad', 2),
    ('LEI', 1, 'Tecnologia de la Informacion', 3),
    ('LEI', 1, 'Ingles II', 3),
    ('LEI', 1, 'Filosofia', 3),
    ('LEI', 2, 'Taller de Creacion Literaria', 3),
    ('LEI', 2, 'Lexicografia', 3),
    ('LEI', 2, 'Ingles I', 3),
    ('LEI', 2, 'Historia Dominicana', 3),
    ('LEI', 3, 'Espanol I', 3),
    ('LEI', 3, 'Practica Docente Lengua II', 5),
    ('LEI', 3, 'Espanol II', 3),
    ('LEI', 3, 'Gramatica Espanola', 4),
    ('LEI', 4, 'Emprendimiento', 3),
    ('LEI', 4, 'Literatura Universal', 4),
    ('LEI', 4, 'Ingles III', 3),
    ('LEI', 4, 'Sociolinguistica', 3),
    ('LEI', 5, 'Linguistica General', 4),
    ('LEI', 5, 'Estadistica General', 4),
    ('LEI', 5, 'Literatura Espanola', 4),
    ('LEI', 5, 'Metodologia de la Investigacion', 3),
    ('LEI', 6, 'Etica Profesional', 2),
    ('LEI', 6, 'Matematica Basica', 4),
    ('LEI', 6, 'Literatura Caribena', 4),
    ('LEI', 6, 'Analisis del Discurso', 3),
    ('LEI', 7, 'Critica Literaria', 3),
    ('LEI', 7, 'Liderazgo', 2),
    ('LEI', 7, 'Psicolinguistica', 3),
    ('LEI', 7, 'Redaccion Academica', 3),
    ('LEI', 8, 'Fonetica y Fonologia', 4),
    ('LEI', 8, 'Correccion de Estilo', 3),
    ('LEI', 8, 'Literatura Dominicana', 4),
    ('LEI', 8, 'Literatura Hispanoamericana', 4),
    ('LEI', 9, 'Dialectologia', 3),
    ('LEI', 9, 'Morfosintaxis II', 4),
    ('LEI', 9, 'Redaccion Academica', 4),
    ('LEI', 9, 'Practica Docente Lengua I', 4),
    ('LEI', 10, 'Teoria Literaria', 4),
    ('LEI', 10, 'Didactica de la Lengua', 4),
    ('LEI', 10, 'Semantica', 3),
    ('LEI', 10, 'Oratoria', 3),
    ('LEI', 11, 'Morfosintaxis I', 4),
    ('LEI', 11, 'Pragmatica', 3),
    ('LEF', 1, 'Gramatica Espanola', 4),
    ('LEF', 1, 'Ingles III', 3),
    ('LEF', 1, 'Lexicografia', 3),
    ('LEF', 1, 'Didactica de la Lengua', 4),
    ('LEF', 2, 'Liderazgo', 2),
    ('LEF', 2, 'Linguistica General', 4),
    ('LEF', 2, 'Analisis del Discurso', 3),
    ('LEF', 2, 'Ingles I', 3),
    ('LEF', 3, 'Ingles II', 3),
    ('LEF', 3, 'Fonetica y Fonologia', 4),
    ('LEF', 3, 'Filosofia', 3),
    ('LEF', 3, 'Matematica Basica', 4),
    ('LEF', 4, 'Medio Ambiente y Sociedad', 2),
    ('LEF', 4, 'Espanol I', 3),
    ('LEF', 4, 'Redaccion Academica', 4),
    ('LEF', 5, 'Psicolinguistica', 3),
    ('LEF', 5, 'Dialectologia', 3),
    ('LEF', 5, 'Practica Docente Lengua II', 5),
    ('LEF', 5, 'Historia Dominicana', 3),
    ('LEF', 6, 'Emprendimiento', 3),
    ('LEF', 6, 'Etica Profesional', 2),
    ('LEF', 6, 'Sociolinguistica', 3),
    ('LEF', 6, 'Literatura Universal', 4),
    ('LEF', 7, 'Estadistica General', 4),
    ('LEF', 7, 'Morfosintaxis II', 4),
    ('LEF', 7, 'Metodologia de la Investigacion', 3),
    ('LEF', 7, 'Critica Literaria', 3),
    ('LEF', 8, 'Tecnologia de la Informacion', 3),
    ('LEF', 8, 'Espanol II', 3),
    ('LEF', 8, 'Literatura Hispanoamericana', 4),
    ('LEF', 8, 'Teoria Literaria', 4),
    ('LEF', 9, 'Morfosintaxis I', 4),
    ('LEF', 9, 'Pragmatica', 3),
    ('LEF', 9, 'Oratoria', 3),
    ('LEF', 9, 'Literatura Caribena', 4),
    ('LEF', 10, 'Semantica', 3),
    ('LEF', 10, 'Correccion de Estilo', 3),
    ('LEF', 10, 'Literatura Dominicana', 4),
    ('LEF', 10, 'Practica Docente Lengua I', 4),
    ('LEF', 11, 'Literatura Espanola', 4),
    ('LEF', 11, 'Taller de Creacion Literaria', 3),
    ('LMF', 1, 'Seminario de Grado', 4),
    ('LMF', 1, 'Medio Ambiente y Sociedad', 2),
    ('LMF', 1, 'Mercadotecnia II', 4),
    ('LMF', 1, 'Planificacion Estrategica', 4),
    ('LMF', 2, 'Emprendimiento', 3),
    ('LMF', 2, 'Innovacion Empresarial', 3),
    ('LMF', 2, 'Espanol II', 3),
    ('LMF', 2, 'Contabilidad II', 4),
    ('LMF', 3, 'Gestion del Talento Humano', 4),
    ('LMF', 3, 'Espanol I', 3),
    ('LMF', 3, 'Historia Dominicana', 3),
    ('LMF', 3, 'Metodologia de la Investigacion', 3),
    ('LMF', 4, 'Gestion de Riesgos', 3),
    ('LMF', 4, 'Comportamiento Organizacional', 3),
    ('LMF', 4, 'Auditoria Administrativa', 3),
    ('LMF', 4, 'Etica Profesional', 2),
    ('LMF', 5, 'Comercio Internacional', 4),
    ('LMF', 5, 'Mercadotecnia I', 4),
    ('LMF', 5, 'Tecnologia de la Informacion', 3),
    ('LMF', 5, 'Filosofia', 3),
    ('LMF', 6, 'Administracion de Empresas', 4),
    ('LMF', 6, 'Ingles III', 3),
    ('LMF', 6, 'Ingles I', 3),
    ('LMF', 6, 'Contabilidad I', 4),
    ('LMF', 7, 'Redaccion Academica', 3),
    ('LMF', 7, 'Derecho Empresarial', 3),
    ('LMF', 7, 'Ingles II', 3),
    ('LMF', 7, 'Negociacion y Resolucion de Conflictos', 3),
    ('LMF', 8, 'Matematica Basica', 4),
    ('LMF', 8, 'Economia Empresarial', 4),
    ('LMF', 8, 'Cadena de Suministro', 4),
    ('LMF', 8, 'Gestion del Cambio', 3),
    ('LMF', 9, 'Estadistica General', 4),
    ('LMF', 9, 'Gestion de Operaciones', 4),
    ('LMF', 9, 'Finanzas Corporativas', 4),
    ('LMF', 9, 'Comercio Electronico', 3),
    ('LMF', 10, 'Liderazgo', 2),
    ('LMF', 10, 'Gestion de la Calidad', 3),
    ('LMF', 10, 'Administracion Publica', 3),
    ('LMF', 10, 'Presupuesto Empresarial', 3),
    ('LMF', 11, 'Toma de Decisiones Gerenciales', 4),
    ('LMF', 11, 'Responsabilidad Social Empresarial', 2),
    ('TS-ADS', 1, 'Redes de Computadoras', 4),
    ('TS-ADS', 1, 'Desarrollo Web', 4),
    ('TS-ADS', 1, 'Filosofia', 3),
    ('TS-ADS', 1, 'Espanol I', 3),
    ('TS-ADS', 2, 'Ingles III', 3),
    ('TS-ADS', 2, 'Estadistica General', 4),
    ('TS-ADS', 2, 'Redaccion Academica', 3),
    ('TS-ADS', 2, 'Sistemas Operativos', 4),
    ('TS-ADS', 3, 'Emprendimiento', 3),
    ('TS-ADS', 3, 'Tecnologia de la Informacion', 3),
    ('TS-ADS', 3, 'Programacion Funcional', 3),
    ('TS-ADS', 3, 'Metodologia de la Investigacion', 3),
    ('TS-ADS', 4, 'Arquitectura de Computadoras', 3),
    ('TS-ADS', 4, 'Proyecto Integrador II', 4),
    ('TS-ADS', 4, 'Bases de Datos I', 4),
    ('TS-ADS', 4, 'Liderazgo', 2),
    ('TS-ADS', 5, 'Bases de Datos II', 4),
    ('TS-ADS', 5, 'Ingenieria de Software II', 4),
    ('TS-ADS', 5, 'Matematica Basica', 4),
    ('TS-ADS', 5, 'Medio Ambiente y Sociedad', 2),
    ('TS-ADS', 6, 'Ingenieria de Software I', 4),
    ('TS-ADS', 6, 'Realidad Virtual y Aumentada', 3),
    ('TS-ADS', 6, 'Analisis y Diseno de Sistemas', 4),
    ('TS-ADS', 6, 'Etica Profesional', 2),
    ('TS-ADS', 7, 'Criptografia', 3),
    ('TS-ADS', 7, 'Computacion en la Nube', 3),
    ('TS-ADS', 7, 'Historia Dominicana', 3),
    ('TS-ADS', 7, 'Ingles II', 3),
    ('TS-ADS', 8, 'Ciencia de Datos', 4),
    ('TS-ADS', 8, 'Espanol II', 3),
    ('TS-ADS', 8, 'Inteligencia Artificial', 4),
    ('TS-ADS', 8, 'Algoritmos Avanzados', 4),
    ('TS-ADS', 9, 'Estructura de Datos', 4),
    ('TS-ADS', 9, 'Compiladores', 4),
    ('TS-ADS', 9, 'Ingles I', 3),
    ('TS-ADS', 9, 'Programacion Orientada a Objetos', 4),
    ('TS-ADS', 10, 'Fundamentos de Programacion', 4),
    ('TS-ADS', 10, 'Seguridad Informatica', 3),
    ('TS-ADS', 10, 'Desarrollo Movil', 4),
    ('TS-ADS', 10, 'Calidad de Software', 3),
    ('TS-ADS', 11, 'Interaccion Humano-Computador', 3),
    ('TS-ADS', 11, 'Sistemas Distribuidos', 3),
    ('TS-ADS', 11, 'Blockchain', 3),
    ('TS-ADS', 11, 'Proyecto Integrador I', 4),
    ('TS-ADS', 12, 'Mineria de Datos', 4),
    ('TS-ADS', 12, 'DevOps', 3),
    ('ISO', 1, 'Ingenieria de Software II', 4),
    ('ISO', 1, 'Programacion Funcional', 3),
    ('ISO', 1, 'Emprendimiento', 3),
    ('ISO', 1, 'Redes de Computadoras', 4),
    ('ISO', 2, 'Inteligencia Artificial', 4),
    ('ISO', 2, 'Compiladores', 4),
    ('ISO', 2, 'Interaccion Humano-Computador', 3),
    ('ISO', 2, 'Liderazgo', 2),
    ('ISO', 3, 'Estructura de Datos', 4),
    ('ISO', 3, 'Filosofia', 3),
    ('ISO', 3, 'Sistemas Distribuidos', 3),
    ('ISO', 3, 'DevOps', 3),
    ('ISO', 4, 'Medio Ambiente y Sociedad', 2),
    ('ISO', 4, 'Espanol I', 3),
    ('ISO', 4, 'Seguridad Informatica', 3),
    ('ISO', 4, 'Ingles III', 3),
    ('ISO', 5, 'Ingles II', 3),
    ('ISO', 5, 'Sistemas Operativos', 4),
    ('ISO', 5, 'Tecnologia de la Informacion', 3),
    ('ISO', 5, 'Blockchain', 3),
    ('ISO', 6, 'Arquitectura de Computadoras', 3),
    ('ISO', 6, 'Bases de Datos I', 4),
    ('ISO', 6, 'Proyecto Integrador II', 4),
    ('ISO', 6, 'Ingenieria de Software I', 4),
    ('ISO', 7, 'Realidad Virtual y Aumentada', 3),
    ('ISO', 7, 'Calidad de Software', 3),
    ('ISO', 7, 'Desarrollo Movil', 4),
    ('ISO', 7, 'Computacion en la Nube', 3),
    ('ISO', 8, 'Ingles I', 3),
    ('ISO', 8, 'Criptografia', 3),
    ('ISO', 8, 'Programacion Orientada a Objetos', 4),
    ('ISO', 8, 'Proyecto Integrador I', 4),
    ('ISO', 9, 'Metodologia de la Investigacion', 3),
    ('ISO', 9, 'Espanol II', 3),
    ('ISO', 9, 'Mineria de Datos', 4),
    ('ISO', 9, 'Analisis y Diseno de Sistemas', 4),
    ('ISO', 10, 'Matematica Basica', 4),
    ('ISO', 10, 'Estadistica General', 4),
    ('ISO', 10, 'Algoritmos Avanzados', 4),
    ('ISO', 10, 'Redaccion Academica', 3),
    ('ISO', 11, 'Historia Dominicana', 3),
    ('ISO', 11, 'Etica Profesional', 2),
    ('ISO', 11, 'Fundamentos de Programacion', 4),
    ('ISO', 11, 'Ciencia de Datos', 4),
    ('ISO', 12, 'Desarrollo Web', 4),
    ('ISO', 12, 'Bases de Datos II', 4),
    ('ISC', 1, 'Ciencia de Datos', 4),
    ('ISC', 1, 'Computacion en la Nube', 3),
    ('ISC', 1, 'Programacion Orientada a Objetos', 4),
    ('ISC', 1, 'Liderazgo', 2),
    ('ISC', 2, 'Bases de Datos II', 4),
    ('ISC', 2, 'Desarrollo Movil', 4),
    ('ISC', 2, 'Tecnologia de la Informacion', 3),
    ('ISC', 2, 'Espanol I', 3),
    ('ISC', 3, 'Redaccion Academica', 3),
    ('ISC', 3, 'Espanol II', 3),
    ('ISC', 3, 'Proyecto Integrador I', 4),
    ('ISC', 3, 'Ingenieria de Software II', 4),
    ('ISC', 4, 'Filosofia', 3),
    ('ISC', 4, 'Analisis y Diseno de Sistemas', 4),
    ('ISC', 4, 'Etica Profesional', 2),
    ('ISC', 4, 'Programacion Funcional', 3),
    ('ISC', 5, 'Fundamentos de Programacion', 4),
    ('ISC', 5, 'Interaccion Humano-Computador', 3),
    ('ISC', 5, 'Sistemas Operativos', 4),
    ('ISC', 5, 'Estadistica General', 4),
    ('ISC', 6, 'Medio Ambiente y Sociedad', 2),
    ('ISC', 6, 'Bases de Datos I', 4),
    ('ISC', 6, 'Historia Dominicana', 3),
    ('ISC', 6, 'Seguridad Informatica', 3),
    ('ISC', 7, 'Sistemas Distribuidos', 3),
    ('ISC', 7, 'Ingles III', 3),
    ('ISC', 7, 'Mineria de Datos', 4),
    ('ISC', 7, 'Emprendimiento', 3),
    ('ISC', 8, 'Desarrollo Web', 4),
    ('ISC', 8, 'Matematica Basica', 4),
    ('ISC', 8, 'Ingles II', 3),
    ('ISC', 8, 'Ingles I', 3),
    ('ISC', 9, 'Arquitectura de Computadoras', 3),
    ('ISC', 9, 'Redes de Computadoras', 4),
    ('ISC', 9, 'Metodologia de la Investigacion', 3),
    ('ISC', 9, 'Compiladores', 4),
    ('ISC', 10, 'Calidad de Software', 3),
    ('ISC', 10, 'Realidad Virtual y Aumentada', 3),
    ('ISC', 10, 'Blockchain', 3),
    ('ISC', 10, 'Estructura de Datos', 4),
    ('ISC', 11, 'Criptografia', 3),
    ('ISC', 11, 'Inteligencia Artificial', 4),
    ('ISC', 11, 'Proyecto Integrador II', 4),
    ('ISC', 11, 'Algoritmos Avanzados', 4),
    ('ISC', 12, 'Ingenieria de Software I', 4),
    ('ISC', 12, 'DevOps', 3),
    ('IND', 1, 'Energias Renovables', 3),
    ('IND', 1, 'Logistica', 4),
    ('IND', 1, 'Proyecto Final de Ingenieria', 5),
    ('IND', 1, 'Ingenieria Economica', 3),
    ('IND', 2, 'Automatizacion Industrial', 4),
    ('IND', 2, 'Investigacion de Operaciones', 4),
    ('IND', 2, 'Metodologia de la Investigacion', 3),
    ('IND', 2, 'Matematica Basica', 4),
    ('IND', 3, 'Historia Dominicana', 3),
    ('IND', 3, 'Circuitos Electricos', 4),
    ('IND', 3, 'Ingles II', 3),
    ('IND', 3, 'Ecuaciones Diferenciales', 4),
    ('IND', 4, 'Gestion de Proyectos de Ingenieria', 4),
    ('IND', 4, 'Calculo III', 5),
    ('IND', 4, 'Robotica', 4),
    ('IND', 4, 'Emprendimiento', 3),
    ('IND', 5, 'Fisica II', 5),
    ('IND', 5, 'Liderazgo', 2),
    ('IND', 5, 'Diseno Mecanico', 4),
    ('IND', 5, 'Espanol I', 3),
    ('IND', 6, 'Tecnologia de la Informacion', 3),
    ('IND', 6, 'Quimica General', 4),
    ('IND', 6, 'Redaccion Academica', 3),
    ('IND', 6, 'Medio Ambiente y Sociedad', 2),
    ('IND', 7, 'Procesos de Manufactura', 4),
    ('IND', 7, 'Etica Profesional', 2),
    ('IND', 7, 'Estadistica General', 4),
    ('IND', 7, 'Instrumentacion', 3),
    ('IND', 8, 'Termodinamica', 4),
    ('IND', 8, 'Ingles I', 3),
    ('IND', 8, 'Calculo II', 5),
    ('IND', 8, 'Fisica I', 5),
    ('IND', 9, 'Calculo I', 5),
    ('IND', 9, 'Sistemas de Potencia', 4),
    ('IND', 9, 'Espanol II', 3),
    ('IND', 9, 'Dibujo Tecnico', 3),
    ('IND', 10, 'Filosofia', 3),
    ('IND', 10, 'Control de Calidad', 3),
    ('IND', 10, 'Mecanica de Materiales', 4),
    ('IND', 10, 'Ingles III', 3),
    ('IND', 11, 'Mantenimiento Industrial', 3),
    ('IND', 11, 'Electronica', 4),
    ('IND', 11, 'Seguridad Industrial', 2),
    ('IND', 11, 'Algebra Lineal', 4),
    ('IEL', 1, 'Etica Profesional', 2),
    ('IEL', 1, 'Comercio Electronico', 3),
    ('IEL', 1, 'Administracion Publica', 3),
    ('IEL', 1, 'Medio Ambiente y Sociedad', 2),
    ('IEL', 2, 'Estadistica General', 4),
    ('IEL', 2, 'Seminario de Grado', 4),
    ('IEL', 2, 'Historia Dominicana', 3),
    ('IEL', 2, 'Innovacion Empresarial', 3),
    ('IEL', 3, 'Emprendimiento', 3),
    ('IEL', 3, 'Contabilidad I', 4),
    ('IEL', 3, 'Gestion de Riesgos', 3),
    ('IEL', 3, 'Matematica Basica', 4),
    ('IEL', 4, 'Responsabilidad Social Empresarial', 2),
    ('IEL', 4, 'Ingles II', 3),
    ('IEL', 4, 'Planificacion Estrategica', 4),
    ('IEL', 4, 'Tecnologia de la Informacion', 3),
    ('IEL', 5, 'Metodologia de la Investigacion', 3),
    ('IEL', 5, 'Toma de Decisiones Gerenciales', 4),
    ('IEL', 5, 'Gestion del Cambio', 3),
    ('IEL', 5, 'Filosofia', 3),
    ('IEL', 6, 'Ingles III', 3),
    ('IEL', 6, 'Espanol I', 3),
    ('IEL', 6, 'Administracion de Empresas', 4),
    ('IEL', 6, 'Ingles I', 3),
    ('IEL', 7, 'Mercadotecnia II', 4),
    ('IEL', 7, 'Liderazgo', 2),
    ('IEL', 7, 'Presupuesto Empresarial', 3),
    ('IEL', 7, 'Gestion del Talento Humano', 4),
    ('IEL', 8, 'Economia Empresarial', 4),
    ('IEL', 8, 'Espanol II', 3),
    ('IEL', 8, 'Redaccion Academica', 3),
    ('IEL', 8, 'Negociacion y Resolucion de Conflictos', 3),
    ('IEL', 9, 'Gestion de Operaciones', 4),
    ('IEL', 9, 'Comportamiento Organizacional', 3),
    ('IEL', 9, 'Contabilidad II', 4),
    ('IEL', 9, 'Cadena de Suministro', 4),
    ('IEL', 10, 'Derecho Empresarial', 3),
    ('IEL', 10, 'Comercio Internacional', 4),
    ('IEL', 10, 'Gestion de la Calidad', 3),
    ('IEL', 10, 'Finanzas Corporativas', 4),
    ('IEL', 11, 'Mercadotecnia I', 4),
    ('IEL', 11, 'Auditoria Administrativa', 3),
    ('INE', 1, 'Toma de Decisiones Gerenciales', 4),
    ('INE', 1, 'Administracion de Empresas', 4),
    ('INE', 1, 'Innovacion Empresarial', 3),
    ('INE', 1, 'Administracion Publica', 3),
    ('INE', 2, 'Emprendimiento', 3),
    ('INE', 2, 'Gestion del Talento Humano', 4),
    ('INE', 2, 'Filosofia', 3),
    ('INE', 2, 'Gestion del Cambio', 3),
    ('INE', 3, 'Liderazgo', 2),
    ('INE', 3, 'Auditoria Administrativa', 3),
    ('INE', 3, 'Contabilidad I', 4),
    ('INE', 3, 'Etica Profesional', 2),
    ('INE', 4, 'Redaccion Academica', 3),
    ('INE', 4, 'Comercio Internacional', 4),
    ('INE', 4, 'Ingles III', 3),
    ('INE', 4, 'Tecnologia de la Informacion', 3),
    ('INE', 5, 'Estadistica General', 4),
    ('INE', 5, 'Matematica Basica', 4),
    ('INE', 5, 'Comercio Electronico', 3),
    ('INE', 5, 'Responsabilidad Social Empresarial', 2),
    ('INE', 6, 'Mercadotecnia I', 4),
    ('INE', 6, 'Planificacion Estrategica', 4),
    ('INE', 6, 'Espanol I', 3),
    ('INE', 6, 'Ingles II', 3),
    ('INE', 7, 'Medio Ambiente y Sociedad', 2),
    ('INE', 7, 'Cadena de Suministro', 4),
    ('INE', 7, 'Metodologia de la Investigacion', 3),
    ('INE', 7, 'Seminario de Grado', 4),
    ('INE', 8, 'Historia Dominicana', 3),
    ('INE', 8, 'Espanol II', 3),
    ('INE', 8, 'Negociacion y Resolucion de Conflictos', 3),
    ('INE', 8, 'Ingles I', 3),
    ('INE', 9, 'Gestion de Riesgos', 3),
    ('INE', 9, 'Finanzas Corporativas', 4),
    ('INE', 9, 'Economia Empresarial', 4),
    ('INE', 9, 'Presupuesto Empresarial', 3),
    ('INE', 10, 'Gestion de Operaciones', 4),
    ('INE', 10, 'Derecho Empresarial', 3),
    ('INE', 10, 'Gestion de la Calidad', 3),
    ('INE', 10, 'Mercadotecnia II', 4),
    ('INE', 11, 'Contabilidad II', 4),
    ('INE', 11, 'Comportamiento Organizacional', 3),
    ('LME', 1, 'Finanzas Corporativas', 4),
    ('LME', 1, 'Seminario de Grado', 4),
    ('LME', 1, 'Ingles I', 3),
    ('LME', 1, 'Administracion Publica', 3),
    ('LME', 2, 'Espanol II', 3),
    ('LME', 2, 'Estadistica General', 4),
    ('LME', 2, 'Medio Ambiente y Sociedad', 2),
    ('LME', 2, 'Metodologia de la Investigacion', 3),
    ('LME', 3, 'Negociacion y Resolucion de Conflictos', 3),
    ('LME', 3, 'Tecnologia de la Informacion', 3),
    ('LME', 3, 'Espanol I', 3),
    ('LME', 3, 'Gestion de Riesgos', 3),
    ('LME', 4, 'Contabilidad II', 4),
    ('LME', 4, 'Comportamiento Organizacional', 3),
    ('LME', 4, 'Comercio Electronico', 3),
    ('LME', 4, 'Historia Dominicana', 3),
    ('LME', 5, 'Redaccion Academica', 3),
    ('LME', 5, 'Matematica Basica', 4),
    ('LME', 5, 'Gestion de Operaciones', 4),
    ('LME', 5, 'Ingles III', 3),
    ('LME', 6, 'Etica Profesional', 2),
    ('LME', 6, 'Ingles II', 3),
    ('LME', 6, 'Contabilidad I', 4),
    ('LME', 6, 'Cadena de Suministro', 4),
    ('LME', 7, 'Liderazgo', 2),
    ('LME', 7, 'Emprendimiento', 3),
    ('LME', 7, 'Gestion del Cambio', 3),
    ('LME', 7, 'Toma de Decisiones Gerenciales', 4),
    ('LME', 8, 'Filosofia', 3),
    ('LME', 8, 'Comercio Internacional', 4),
    ('LME', 8, 'Planificacion Estrategica', 4),
    ('LME', 8, 'Administracion de Empresas', 4),
    ('LME', 9, 'Presupuesto Empresarial', 3),
    ('LME', 9, 'Innovacion Empresarial', 3),
    ('LME', 9, 'Responsabilidad Social Empresarial', 2),
    ('LME', 9, 'Mercadotecnia I', 4),
    ('LME', 10, 'Auditoria Administrativa', 3),
    ('LME', 10, 'Derecho Empresarial', 3),
    ('LME', 10, 'Gestion del Talento Humano', 4),
    ('LME', 10, 'Mercadotecnia II', 4),
    ('LME', 11, 'Economia Empresarial', 4),
    ('LME', 11, 'Gestion de la Calidad', 3),
    ('EST', 1, 'Ingles II', 3),
    ('EST', 1, 'Derecho Empresarial', 3),
    ('EST', 1, 'Cadena de Suministro', 4),
    ('EST', 1, 'Ingles III', 3),
    ('EST', 2, 'Administracion Publica', 3),
    ('EST', 2, 'Gestion de Operaciones', 4),
    ('EST', 2, 'Auditoria Administrativa', 3),
    ('EST', 2, 'Comercio Internacional', 4),
    ('EST', 3, 'Metodologia de la Investigacion', 3),
    ('EST', 3, 'Espanol I', 3),
    ('EST', 3, 'Liderazgo', 2),
    ('EST', 3, 'Etica Profesional', 2),
    ('EST', 4, 'Filosofia', 3),
    ('EST', 4, 'Gestion del Cambio', 3),
    ('EST', 4, 'Contabilidad II', 4),
    ('EST', 4, 'Contabilidad I', 4),
    ('EST', 5, 'Tecnologia de la Informacion', 3),
    ('EST', 5, 'Mercadotecnia II', 4),
    ('EST', 5, 'Comercio Electronico', 3),
    ('EST', 5, 'Mercadotecnia I', 4),
    ('EST', 6, 'Emprendimiento', 3),
    ('EST', 6, 'Historia Dominicana', 3),
    ('EST', 6, 'Medio Ambiente y Sociedad', 2),
    ('EST', 6, 'Matematica Basica', 4),
    ('EST', 7, 'Negociacion y Resolucion de Conflictos', 3),
    ('EST', 7, 'Redaccion Academica', 3),
    ('EST', 7, 'Planificacion Estrategica', 4),
    ('EST', 7, 'Presupuesto Empresarial', 3),
    ('EST', 8, 'Administracion de Empresas', 4),
    ('EST', 8, 'Estadistica General', 4),
    ('EST', 8, 'Finanzas Corporativas', 4),
    ('EST', 8, 'Espanol II', 3),
    ('EST', 9, 'Comportamiento Organizacional', 3),
    ('EST', 9, 'Ingles I', 3),
    ('EST', 9, 'Gestion de Riesgos', 3),
    ('EST', 9, 'Gestion de la Calidad', 3),
    ('EST', 10, 'Economia Empresarial', 4),
    ('EST', 10, 'Toma de Decisiones Gerenciales', 4),
    ('EST', 10, 'Responsabilidad Social Empresarial', 2),
    ('EST', 10, 'Gestion del Talento Humano', 4),
    ('EST', 11, 'Innovacion Empresarial', 3),
    ('EST', 11, 'Seminario de Grado', 4),
    ('TS-EM', 1, 'Emprendimiento', 3),
    ('TS-EM', 1, 'Responsabilidad Social', 2),
    ('TS-EM', 1, 'Ventas y Negociacion', 4),
    ('TS-EM', 1, 'Matematica Basica', 4),
    ('TS-EM', 2, 'Investigacion de Mercados', 4),
    ('TS-EM', 2, 'Mercadeo de Servicios', 3),
    ('TS-EM', 2, 'Geopolitica', 3),
    ('TS-EM', 2, 'Mercadeo Relacional', 3),
    ('TS-EM', 3, 'Economia Global', 3),
    ('TS-EM', 3, 'Etica Profesional', 2),
    ('TS-EM', 3, 'Espanol II', 3),
    ('TS-EM', 3, 'Fundamentos de Mercadeo', 4),
    ('TS-EM', 4, 'Transporte Internacional', 3),
    ('TS-EM', 4, 'Metodologia de la Investigacion', 3),
    ('TS-EM', 4, 'Filosofia', 3),
    ('TS-EM', 4, 'Precios y Rentabilidad', 3),
    ('TS-EM', 5, 'Finanzas Internacionales', 4),
    ('TS-EM', 5, 'Inteligencia de Mercados', 4),
    ('TS-EM', 5, 'Ingles I', 3),
    ('TS-EM', 5, 'Medio Ambiente y Sociedad', 2),
    ('TS-EM', 6, 'Seminario de Mercadeo', 4),
    ('TS-EM', 6, 'Historia Dominicana', 3),
    ('TS-EM', 6, 'Redaccion Academica', 3),
    ('TS-EM', 6, 'Estadistica General', 4),
    ('TS-EM', 7, 'Espanol I', 3),
    ('TS-EM', 7, 'Comercio Internacional II', 4),
    ('TS-EM', 7, 'Ingles III', 3),
    ('TS-EM', 7, 'Publicidad y Promocion', 4),
    ('TS-EM', 8, 'Cadena de Suministro Global', 4),
    ('TS-EM', 8, 'Ingles II', 3),
    ('TS-EM', 8, 'Derecho del Comercio Exterior', 3),
    ('TS-EM', 8, 'Liderazgo', 2),
    ('TS-EM', 9, 'Estrategia de Marca', 4),
    ('TS-EM', 9, 'Comportamiento del Consumidor', 4),
    ('TS-EM', 9, 'Negocios Internacionales', 4),
    ('TS-EM', 9, 'Logistica Global', 4),
    ('TS-EM', 10, 'Tecnologia de la Informacion', 3),
    ('TS-EM', 10, 'Estrategias de Exportacion', 4),
    ('TS-EM', 10, 'Innovacion de Productos', 3),
    ('TS-EM', 10, 'Mercadeo Digital', 4),
    ('TS-EM', 11, 'Distribucion y Logistica', 4),
    ('TS-EM', 11, 'Aduanas y Aranceles', 3),
    ('NIN', 1, 'Estadistica General', 4),
    ('NIN', 1, 'Metodologia de la Investigacion', 3),
    ('NIN', 1, 'Ingles III', 3),
    ('NIN', 1, 'Mercadeo de Servicios', 3),
    ('NIN', 2, 'Ventas y Negociacion', 4),
    ('NIN', 2, 'Ingles I', 3),
    ('NIN', 2, 'Geopolitica', 3),
    ('NIN', 2, 'Redaccion Academica', 3),
    ('NIN', 3, 'Etica Profesional', 2),
    ('NIN', 3, 'Transporte Internacional', 3),
    ('NIN', 3, 'Fundamentos de Mercadeo', 4),
    ('NIN', 3, 'Derecho del Comercio Exterior', 3),
    ('NIN', 4, 'Estrategias de Exportacion', 4),
    ('NIN', 4, 'Matematica Basica', 4),
    ('NIN', 4, 'Comportamiento del Consumidor', 4),
    ('NIN', 4, 'Espanol I', 3),
    ('NIN', 5, 'Espanol II', 3),
    ('NIN', 5, 'Filosofia', 3),
    ('NIN', 5, 'Medio Ambiente y Sociedad', 2),
    ('NIN', 5, 'Tecnologia de la Informacion', 3),
    ('NIN', 6, 'Inteligencia de Mercados', 4),
    ('NIN', 6, 'Ingles II', 3),
    ('NIN', 6, 'Finanzas Internacionales', 4),
    ('NIN', 6, 'Historia Dominicana', 3),
    ('NIN', 7, 'Emprendimiento', 3),
    ('NIN', 7, 'Responsabilidad Social', 2),
    ('NIN', 7, 'Negocios Internacionales', 4),
    ('NIN', 7, 'Liderazgo', 2),
    ('NIN', 8, 'Publicidad y Promocion', 4),
    ('NIN', 8, 'Innovacion de Productos', 3),
    ('NIN', 8, 'Cadena de Suministro Global', 4),
    ('NIN', 8, 'Estrategia de Marca', 4),
    ('NIN', 9, 'Investigacion de Mercados', 4),
    ('NIN', 9, 'Comercio Internacional II', 4),
    ('NIN', 9, 'Logistica Global', 4),
    ('NIN', 9, 'Aduanas y Aranceles', 3),
    ('NIN', 10, 'Precios y Rentabilidad', 3),
    ('NIN', 10, 'Seminario de Mercadeo', 4),
    ('NIN', 10, 'Mercadeo Relacional', 3),
    ('NIN', 10, 'Economia Global', 3),
    ('NIN', 11, 'Distribucion y Logistica', 4),
    ('NIN', 11, 'Mercadeo Digital', 4),
    ('MER', 1, 'Mercadeo Relacional', 3),
    ('MER', 1, 'Ingles III', 3),
    ('MER', 1, 'Logistica Global', 4),
    ('MER', 1, 'Tecnologia de la Informacion', 3),
    ('MER', 2, 'Redaccion Academica', 3),
    ('MER', 2, 'Investigacion de Mercados', 4),
    ('MER', 2, 'Fundamentos de Mercadeo', 4),
    ('MER', 2, 'Espanol II', 3),
    ('MER', 3, 'Metodologia de la Investigacion', 3),
    ('MER', 3, 'Geopolitica', 3),
    ('MER', 3, 'Liderazgo', 2),
    ('MER', 3, 'Aduanas y Aranceles', 3),
    ('MER', 4, 'Historia Dominicana', 3),
    ('MER', 4, 'Matematica Basica', 4),
    ('MER', 4, 'Etica Profesional', 2),
    ('MER', 4, 'Ingles II', 3),
    ('MER', 5, 'Innovacion de Productos', 3),
    ('MER', 5, 'Emprendimiento', 3),
    ('MER', 5, 'Espanol I', 3),
    ('MER', 5, 'Estrategias de Exportacion', 4),
    ('MER', 6, 'Filosofia', 3),
    ('MER', 6, 'Medio Ambiente y Sociedad', 2),
    ('MER', 6, 'Comercio Internacional II', 4),
    ('MER', 6, 'Distribucion y Logistica', 4),
    ('MER', 7, 'Mercadeo de Servicios', 3),
    ('MER', 7, 'Ingles I', 3),
    ('MER', 7, 'Derecho del Comercio Exterior', 3),
    ('MER', 7, 'Estadistica General', 4),
    ('MER', 8, 'Comportamiento del Consumidor', 4),
    ('MER', 8, 'Estrategia de Marca', 4),
    ('MER', 8, 'Mercadeo Digital', 4),
    ('MER', 8, 'Responsabilidad Social', 2),
    ('MER', 9, 'Cadena de Suministro Global', 4),
    ('MER', 9, 'Finanzas Internacionales', 4),
    ('MER', 9, 'Negocios Internacionales', 4),
    ('MER', 9, 'Ventas y Negociacion', 4),
    ('MER', 10, 'Transporte Internacional', 3),
    ('MER', 10, 'Seminario de Mercadeo', 4),
    ('MER', 10, 'Inteligencia de Mercados', 4),
    ('MER', 10, 'Publicidad y Promocion', 4),
    ('MER', 11, 'Precios y Rentabilidad', 3),
    ('MER', 11, 'Economia Global', 3),
    ('TS-TH', 1, 'Historia Dominicana', 3),
    ('TS-TH', 1, 'Derecho Empresarial', 3),
    ('TS-TH', 1, 'Innovacion Empresarial', 3),
    ('TS-TH', 1, 'Planificacion Estrategica', 4),
    ('TS-TH', 2, 'Espanol I', 3),
    ('TS-TH', 2, 'Etica Profesional', 2),
    ('TS-TH', 2, 'Emprendimiento', 3),
    ('TS-TH', 2, 'Administracion Publica', 3),
    ('TS-TH', 3, 'Filosofia', 3),
    ('TS-TH', 3, 'Espanol II', 3),
    ('TS-TH', 3, 'Matematica Basica', 4),
    ('TS-TH', 3, 'Gestion de Riesgos', 3),
    ('TS-TH', 4, 'Liderazgo', 2),
    ('TS-TH', 4, 'Gestion del Talento Humano', 4),
    ('TS-TH', 4, 'Mercadotecnia II', 4),
    ('TS-TH', 4, 'Medio Ambiente y Sociedad', 2),
    ('TS-TH', 5, 'Ingles III', 3),
    ('TS-TH', 5, 'Tecnologia de la Informacion', 3),
    ('TS-TH', 5, 'Metodologia de la Investigacion', 3),
    ('TS-TH', 5, 'Redaccion Academica', 3),
    ('TS-TH', 6, 'Administracion de Empresas', 4),
    ('TS-TH', 6, 'Cadena de Suministro', 4),
    ('TS-TH', 6, 'Contabilidad I', 4),
    ('TS-TH', 6, 'Contabilidad II', 4),
    ('TS-TH', 7, 'Comercio Electronico', 3),
    ('TS-TH', 7, 'Gestion de Operaciones', 4),
    ('TS-TH', 7, 'Economia Empresarial', 4),
    ('TS-TH', 7, 'Ingles II', 3),
    ('TS-TH', 8, 'Toma de Decisiones Gerenciales', 4),
    ('TS-TH', 8, 'Estadistica General', 4),
    ('TS-TH', 8, 'Ingles I', 3),
    ('TS-TH', 8, 'Comportamiento Organizacional', 3),
    ('TS-TH', 9, 'Presupuesto Empresarial', 3),
    ('TS-TH', 9, 'Mercadotecnia I', 4),
    ('TS-TH', 9, 'Seminario de Grado', 4),
    ('TS-TH', 9, 'Auditoria Administrativa', 3),
    ('TS-TH', 10, 'Gestion de la Calidad', 3),
    ('TS-TH', 10, 'Gestion del Cambio', 3),
    ('TS-TH', 10, 'Comercio Internacional', 4),
    ('TS-TH', 10, 'Finanzas Corporativas', 4),
    ('TS-TH', 11, 'Negociacion y Resolucion de Conflictos', 3),
    ('TS-TH', 11, 'Responsabilidad Social Empresarial', 2),
    ('TS-GSA', 1, 'Turismo Sostenible', 3),
    ('TS-GSA', 1, 'Gestion de Eventos', 4),
    ('TS-GSA', 1, 'Ingles I', 3),
    ('TS-GSA', 1, 'Tecnologia de la Informacion', 3),
    ('TS-GSA', 2, 'Protocolo y Etiqueta', 2),
    ('TS-GSA', 2, 'Cocina Dominicana', 4),
    ('TS-GSA', 2, 'Etica Profesional', 2),
    ('TS-GSA', 2, 'Filosofia', 3),
    ('TS-GSA', 3, 'Patrimonio Cultural', 3),
    ('TS-GSA', 3, 'Liderazgo', 2),
    ('TS-GSA', 3, 'Introduccion al Turismo', 4),
    ('TS-GSA', 3, 'Administracion Hotelera', 4),
    ('TS-GSA', 4, 'Estadistica General', 4),
    ('TS-GSA', 4, 'Ingles II', 3),
    ('TS-GSA', 4, 'Tecnologia Aplicada al Turismo', 3),
    ('TS-GSA', 4, 'Cruceros y Viajes', 3),
    ('TS-GSA', 5, 'Gestion de Alimentos y Bebidas', 4),
    ('TS-GSA', 5, 'Medio Ambiente y Sociedad', 2),
    ('TS-GSA', 5, 'Emprendimiento', 3),
    ('TS-GSA', 5, 'Ingles III', 3),
    ('TS-GSA', 6, 'Redaccion Academica', 3),
    ('TS-GSA', 6, 'Espanol I', 3),
    ('TS-GSA', 6, 'Matematica Basica', 4),
    ('TS-GSA', 6, 'Metodologia de la Investigacion', 3),
    ('TS-GSA', 7, 'Espanol II', 3),
    ('TS-GSA', 7, 'Historia Dominicana', 3),
    ('TS-GSA', 7, 'Mercadeo Turistico', 4),
    ('TS-GSA', 7, 'Planificacion Turistica', 4),
    ('TS-GSA', 8, 'Turismo de Aventura', 3),
    ('TS-GSA', 8, 'Negocios Turisticos', 3),
    ('TS-GSA', 8, 'Enologia y Maridaje', 3),
    ('TS-GSA', 8, 'Calidad en el Servicio', 3),
    ('TS-GSA', 9, 'Geografia Turistica Dominicana', 4),
    ('TS-GSA', 9, 'Idiomas para Turismo', 3),
    ('TS-GSA', 9, 'Animacion Turistica', 3),
    ('TS-GSA', 9, 'Contabilidad Hotelera', 3),
    ('TS-GSA', 10, 'Gastronomia Internacional', 4),
    ('TS-GSA', 10, 'Legislacion Turistica', 3),
    ('TS-GSA', 10, 'Operacion de Aerolineas', 3),
    ('TS-GSA', 10, 'Gestion de Destinos', 4),
    ('TS-GSA', 11, 'Reposteria y Panaderia', 4),
    ('TS-GSA', 11, 'Ecoturismo', 3),
    ('GAS', 1, 'Ingles III', 3),
    ('GAS', 1, 'Redaccion Academica', 3),
    ('GAS', 1, 'Animacion Turistica', 3),
    ('GAS', 1, 'Tecnologia Aplicada al Turismo', 3),
    ('GAS', 2, 'Legislacion Turistica', 3),
    ('GAS', 2, 'Reposteria y Panaderia', 4),
    ('GAS', 2, 'Planificacion Turistica', 4),
    ('GAS', 2, 'Protocolo y Etiqueta', 2),
    ('GAS', 3, 'Metodologia de la Investigacion', 3),
    ('GAS', 3, 'Introduccion al Turismo', 4),
    ('GAS', 3, 'Liderazgo', 2),
    ('GAS', 3, 'Emprendimiento', 3),
    ('GAS', 4, 'Tecnologia de la Informacion', 3),
    ('GAS', 4, 'Filosofia', 3),
    ('GAS', 4, 'Contabilidad Hotelera', 3),
    ('GAS', 4, 'Espanol I', 3),
    ('GAS', 5, 'Matematica Basica', 4),
    ('GAS', 5, 'Espanol II', 3),
    ('GAS', 5, 'Ingles I', 3),
    ('GAS', 5, 'Gestion de Alimentos y Bebidas', 4),
    ('GAS', 6, 'Idiomas para Turismo', 3),
    ('GAS', 6, 'Medio Ambiente y Sociedad', 2),
    ('GAS', 6, 'Ingles II', 3),
    ('GAS', 6, 'Historia Dominicana', 3),
    ('GAS', 7, 'Geografia Turistica Dominicana', 4),
    ('GAS', 7, 'Etica Profesional', 2),
    ('GAS', 7, 'Estadistica General', 4),
    ('GAS', 7, 'Patrimonio Cultural', 3),
    ('GAS', 8, 'Enologia y Maridaje', 3),
    ('GAS', 8, 'Operacion de Aerolineas', 3),
    ('GAS', 8, 'Negocios Turisticos', 3),
    ('GAS', 8, 'Ecoturismo', 3),
    ('GAS', 9, 'Administracion Hotelera', 4),
    ('GAS', 9, 'Gastronomia Internacional', 4),
    ('GAS', 9, 'Turismo de Aventura', 3),
    ('GAS', 9, 'Cruceros y Viajes', 3),
    ('GAS', 10, 'Calidad en el Servicio', 3),
    ('GAS', 10, 'Gestion de Destinos', 4),
    ('GAS', 10, 'Mercadeo Turistico', 4),
    ('GAS', 10, 'Cocina Dominicana', 4),
    ('GAS', 11, 'Turismo Sostenible', 3),
    ('GAS', 11, 'Gestion de Eventos', 4),
    ('ATH', 1, 'Ecoturismo', 3),
    ('ATH', 1, 'Introduccion al Turismo', 4),
    ('ATH', 1, 'Ingles III', 3),
    ('ATH', 1, 'Matematica Basica', 4),
    ('ATH', 2, 'Espanol I', 3),
    ('ATH', 2, 'Redaccion Academica', 3),
    ('ATH', 2, 'Espanol II', 3),
    ('ATH', 2, 'Ingles I', 3),
    ('ATH', 3, 'Gestion de Destinos', 4),
    ('ATH', 3, 'Cruceros y Viajes', 3),
    ('ATH', 3, 'Emprendimiento', 3),
    ('ATH', 3, 'Estadistica General', 4),
    ('ATH', 4, 'Tecnologia de la Informacion', 3),
    ('ATH', 4, 'Operacion de Aerolineas', 3),
    ('ATH', 4, 'Reposteria y Panaderia', 4),
    ('ATH', 4, 'Metodologia de la Investigacion', 3),
    ('ATH', 5, 'Historia Dominicana', 3),
    ('ATH', 5, 'Ingles II', 3),
    ('ATH', 5, 'Medio Ambiente y Sociedad', 2),
    ('ATH', 5, 'Planificacion Turistica', 4),
    ('ATH', 6, 'Protocolo y Etiqueta', 2),
    ('ATH', 6, 'Mercadeo Turistico', 4),
    ('ATH', 6, 'Liderazgo', 2),
    ('ATH', 6, 'Gastronomia Internacional', 4),
    ('ATH', 7, 'Filosofia', 3),
    ('ATH', 7, 'Etica Profesional', 2),
    ('ATH', 7, 'Contabilidad Hotelera', 3),
    ('ATH', 7, 'Turismo de Aventura', 3),
    ('ATH', 8, 'Legislacion Turistica', 3),
    ('ATH', 8, 'Cocina Dominicana', 4),
    ('ATH', 8, 'Gestion de Eventos', 4),
    ('ATH', 8, 'Turismo Sostenible', 3),
    ('ATH', 9, 'Patrimonio Cultural', 3),
    ('ATH', 9, 'Tecnologia Aplicada al Turismo', 3),
    ('ATH', 9, 'Administracion Hotelera', 4),
    ('ATH', 9, 'Negocios Turisticos', 3),
    ('ATH', 10, 'Geografia Turistica Dominicana', 4),
    ('ATH', 10, 'Animacion Turistica', 3),
    ('ATH', 10, 'Calidad en el Servicio', 3),
    ('ATH', 10, 'Gestion de Alimentos y Bebidas', 4),
    ('ATH', 11, 'Enologia y Maridaje', 3),
    ('ATH', 11, 'Idiomas para Turismo', 3)
) AS data(career_code, term, subject, credits)
INNER JOIN careers AS c ON c.code = data.career_code
ON CONFLICT (career_id, term_number, subject_name) DO NOTHING;

